/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AbiturFachbelegung from './model/AbiturFachbelegung';
import AbiturFachbelegungHalbjahr from './model/AbiturFachbelegungHalbjahr';
import Abiturdaten from './model/Abiturdaten';
import AbschlussErgebnis from './model/AbschlussErgebnis';
import AbschlussFach from './model/AbschlussFach';
import AbschlussFaecher from './model/AbschlussFaecher';
import BelegpruefungErgebnis from './model/BelegpruefungErgebnis';
import BelegpruefungErgebnisFehler from './model/BelegpruefungErgebnisFehler';
import BenutzerKennwort from './model/BenutzerKennwort';
import ClientKonfiguration from './model/ClientKonfiguration';
import FaecherlisteEintrag from './model/FaecherlisteEintrag';
import GOStFach from './model/GOStFach';
import GOStLeistungen from './model/GOStLeistungen';
import GOStLeistungenFachbelegung from './model/GOStLeistungenFachbelegung';
import GOStLeistungenFachwahl from './model/GOStLeistungenFachwahl';
import KatalogEintrag from './model/KatalogEintrag';
import LehrerKatalogAbgangsgrundEintrag from './model/LehrerKatalogAbgangsgrundEintrag';
import LehrerKatalogBeschaeftigungsartEintrag from './model/LehrerKatalogBeschaeftigungsartEintrag';
import LehrerKatalogEinsatzstatusEintrag from './model/LehrerKatalogEinsatzstatusEintrag';
import LehrerKatalogLeitungsfunktionEintrag from './model/LehrerKatalogLeitungsfunktionEintrag';
import LehrerKatalogRechtsverhaeltnisEintrag from './model/LehrerKatalogRechtsverhaeltnisEintrag';
import LehrerKatalogZugangsgrundEintrag from './model/LehrerKatalogZugangsgrundEintrag';
import LehrerPersonaldaten from './model/LehrerPersonaldaten';
import LehrerStammdaten from './model/LehrerStammdaten';
import LehrerlisteEintrag from './model/LehrerlisteEintrag';
import NationalitaetenKatalogEintrag from './model/NationalitaetenKatalogEintrag';
import OrtKatalogEintrag from './model/OrtKatalogEintrag';
import OrtsteilKatalogEintrag from './model/OrtsteilKatalogEintrag';
import ReligionKatalogEintrag from './model/ReligionKatalogEintrag';
import SchuelerStammdaten from './model/SchuelerStammdaten';
import SchuelerlisteEintrag from './model/SchuelerlisteEintrag';
import Sprachbelegung from './model/Sprachbelegung';
import Sprachenfolge from './model/Sprachenfolge';
import AbschlussGEApi from './api/AbschlussGEApi';
import AbschlussGOStApi from './api/AbschlussGOStApi';
import ClientApi from './api/ClientApi';
import DebugOpenAPIApi from './api/DebugOpenAPIApi';
import FaecherApi from './api/FaecherApi';
import KatalogeApi from './api/KatalogeApi';
import LehrerApi from './api/LehrerApi';
import SchemaApi from './api/SchemaApi';
import SchuelerApi from './api/SchuelerApi';
import SchuelerGOStApi from './api/SchuelerGOStApi';
import SystemApi from './api/SystemApi';


/**
* Ein_Server_fr_die_Bereitstellung_der_Open_API_eines_SVWS_Servers_und_Anwendungen_zum_Zugriff_auf_die_Daten_dieses_Servers_auf__https__localhost_https__localhost_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SvwsOpenApi = require('index'); // See note below*.
* var xxxSvc = new SvwsOpenApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SvwsOpenApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SvwsOpenApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SvwsOpenApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AbiturFachbelegung model constructor.
     * @property {module:model/AbiturFachbelegung}
     */
    AbiturFachbelegung,

    /**
     * The AbiturFachbelegungHalbjahr model constructor.
     * @property {module:model/AbiturFachbelegungHalbjahr}
     */
    AbiturFachbelegungHalbjahr,

    /**
     * The Abiturdaten model constructor.
     * @property {module:model/Abiturdaten}
     */
    Abiturdaten,

    /**
     * The AbschlussErgebnis model constructor.
     * @property {module:model/AbschlussErgebnis}
     */
    AbschlussErgebnis,

    /**
     * The AbschlussFach model constructor.
     * @property {module:model/AbschlussFach}
     */
    AbschlussFach,

    /**
     * The AbschlussFaecher model constructor.
     * @property {module:model/AbschlussFaecher}
     */
    AbschlussFaecher,

    /**
     * The BelegpruefungErgebnis model constructor.
     * @property {module:model/BelegpruefungErgebnis}
     */
    BelegpruefungErgebnis,

    /**
     * The BelegpruefungErgebnisFehler model constructor.
     * @property {module:model/BelegpruefungErgebnisFehler}
     */
    BelegpruefungErgebnisFehler,

    /**
     * The BenutzerKennwort model constructor.
     * @property {module:model/BenutzerKennwort}
     */
    BenutzerKennwort,

    /**
     * The ClientKonfiguration model constructor.
     * @property {module:model/ClientKonfiguration}
     */
    ClientKonfiguration,

    /**
     * The FaecherlisteEintrag model constructor.
     * @property {module:model/FaecherlisteEintrag}
     */
    FaecherlisteEintrag,

    /**
     * The GOStFach model constructor.
     * @property {module:model/GOStFach}
     */
    GOStFach,

    /**
     * The GOStLeistungen model constructor.
     * @property {module:model/GOStLeistungen}
     */
    GOStLeistungen,

    /**
     * The GOStLeistungenFachbelegung model constructor.
     * @property {module:model/GOStLeistungenFachbelegung}
     */
    GOStLeistungenFachbelegung,

    /**
     * The GOStLeistungenFachwahl model constructor.
     * @property {module:model/GOStLeistungenFachwahl}
     */
    GOStLeistungenFachwahl,

    /**
     * The KatalogEintrag model constructor.
     * @property {module:model/KatalogEintrag}
     */
    KatalogEintrag,

    /**
     * The LehrerKatalogAbgangsgrundEintrag model constructor.
     * @property {module:model/LehrerKatalogAbgangsgrundEintrag}
     */
    LehrerKatalogAbgangsgrundEintrag,

    /**
     * The LehrerKatalogBeschaeftigungsartEintrag model constructor.
     * @property {module:model/LehrerKatalogBeschaeftigungsartEintrag}
     */
    LehrerKatalogBeschaeftigungsartEintrag,

    /**
     * The LehrerKatalogEinsatzstatusEintrag model constructor.
     * @property {module:model/LehrerKatalogEinsatzstatusEintrag}
     */
    LehrerKatalogEinsatzstatusEintrag,

    /**
     * The LehrerKatalogLeitungsfunktionEintrag model constructor.
     * @property {module:model/LehrerKatalogLeitungsfunktionEintrag}
     */
    LehrerKatalogLeitungsfunktionEintrag,

    /**
     * The LehrerKatalogRechtsverhaeltnisEintrag model constructor.
     * @property {module:model/LehrerKatalogRechtsverhaeltnisEintrag}
     */
    LehrerKatalogRechtsverhaeltnisEintrag,

    /**
     * The LehrerKatalogZugangsgrundEintrag model constructor.
     * @property {module:model/LehrerKatalogZugangsgrundEintrag}
     */
    LehrerKatalogZugangsgrundEintrag,

    /**
     * The LehrerPersonaldaten model constructor.
     * @property {module:model/LehrerPersonaldaten}
     */
    LehrerPersonaldaten,

    /**
     * The LehrerStammdaten model constructor.
     * @property {module:model/LehrerStammdaten}
     */
    LehrerStammdaten,

    /**
     * The LehrerlisteEintrag model constructor.
     * @property {module:model/LehrerlisteEintrag}
     */
    LehrerlisteEintrag,

    /**
     * The NationalitaetenKatalogEintrag model constructor.
     * @property {module:model/NationalitaetenKatalogEintrag}
     */
    NationalitaetenKatalogEintrag,

    /**
     * The OrtKatalogEintrag model constructor.
     * @property {module:model/OrtKatalogEintrag}
     */
    OrtKatalogEintrag,

    /**
     * The OrtsteilKatalogEintrag model constructor.
     * @property {module:model/OrtsteilKatalogEintrag}
     */
    OrtsteilKatalogEintrag,

    /**
     * The ReligionKatalogEintrag model constructor.
     * @property {module:model/ReligionKatalogEintrag}
     */
    ReligionKatalogEintrag,

    /**
     * The SchuelerStammdaten model constructor.
     * @property {module:model/SchuelerStammdaten}
     */
    SchuelerStammdaten,

    /**
     * The SchuelerlisteEintrag model constructor.
     * @property {module:model/SchuelerlisteEintrag}
     */
    SchuelerlisteEintrag,

    /**
     * The Sprachbelegung model constructor.
     * @property {module:model/Sprachbelegung}
     */
    Sprachbelegung,

    /**
     * The Sprachenfolge model constructor.
     * @property {module:model/Sprachenfolge}
     */
    Sprachenfolge,

    /**
    * The AbschlussGEApi service constructor.
    * @property {module:api/AbschlussGEApi}
    */
    AbschlussGEApi,

    /**
    * The AbschlussGOStApi service constructor.
    * @property {module:api/AbschlussGOStApi}
    */
    AbschlussGOStApi,

    /**
    * The ClientApi service constructor.
    * @property {module:api/ClientApi}
    */
    ClientApi,

    /**
    * The DebugOpenAPIApi service constructor.
    * @property {module:api/DebugOpenAPIApi}
    */
    DebugOpenAPIApi,

    /**
    * The FaecherApi service constructor.
    * @property {module:api/FaecherApi}
    */
    FaecherApi,

    /**
    * The KatalogeApi service constructor.
    * @property {module:api/KatalogeApi}
    */
    KatalogeApi,

    /**
    * The LehrerApi service constructor.
    * @property {module:api/LehrerApi}
    */
    LehrerApi,

    /**
    * The SchemaApi service constructor.
    * @property {module:api/SchemaApi}
    */
    SchemaApi,

    /**
    * The SchuelerApi service constructor.
    * @property {module:api/SchuelerApi}
    */
    SchuelerApi,

    /**
    * The SchuelerGOStApi service constructor.
    * @property {module:api/SchuelerGOStApi}
    */
    SchuelerGOStApi,

    /**
    * The SystemApi service constructor.
    * @property {module:api/SystemApi}
    */
    SystemApi
};
