/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.KatalogeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('KatalogeApi', function() {
    describe('getKatalogHaltestellen', function() {
      it('should call getKatalogHaltestellen successfully', function(done) {
        //uncomment below and update the code to test getKatalogHaltestellen
        //instance.getKatalogHaltestellen(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getKatalogVerkehrssprache', function() {
      it('should call getKatalogVerkehrssprache successfully', function(done) {
        //uncomment below and update the code to test getKatalogVerkehrssprache
        //instance.getKatalogVerkehrssprache(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNationaelitaetenKatalog', function() {
      it('should call getNationaelitaetenKatalog successfully', function(done) {
        //uncomment below and update the code to test getNationaelitaetenKatalog
        //instance.getNationaelitaetenKatalog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrtKatalog', function() {
      it('should call getOrtKatalog successfully', function(done) {
        //uncomment below and update the code to test getOrtKatalog
        //instance.getOrtKatalog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrtsteilKatalog', function() {
      it('should call getOrtsteilKatalog successfully', function(done) {
        //uncomment below and update the code to test getOrtsteilKatalog
        //instance.getOrtsteilKatalog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReligionKatalog', function() {
      it('should call getReligionKatalog successfully', function(done) {
        //uncomment below and update the code to test getReligionKatalog
        //instance.getReligionKatalog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
