/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.LehrerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LehrerApi', function() {
    describe('getLehrerKatalogAbgangsgrund', function() {
      it('should call getLehrerKatalogAbgangsgrund successfully', function(done) {
        //uncomment below and update the code to test getLehrerKatalogAbgangsgrund
        //instance.getLehrerKatalogAbgangsgrund(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLehrerKatalogBeschaeftigungsart', function() {
      it('should call getLehrerKatalogBeschaeftigungsart successfully', function(done) {
        //uncomment below and update the code to test getLehrerKatalogBeschaeftigungsart
        //instance.getLehrerKatalogBeschaeftigungsart(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLehrerKatalogEinsatzstatus', function() {
      it('should call getLehrerKatalogEinsatzstatus successfully', function(done) {
        //uncomment below and update the code to test getLehrerKatalogEinsatzstatus
        //instance.getLehrerKatalogEinsatzstatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLehrerKatalogLeitungsfunktion', function() {
      it('should call getLehrerKatalogLeitungsfunktion successfully', function(done) {
        //uncomment below and update the code to test getLehrerKatalogLeitungsfunktion
        //instance.getLehrerKatalogLeitungsfunktion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLehrerKatalogRechtsverhaeltnis', function() {
      it('should call getLehrerKatalogRechtsverhaeltnis successfully', function(done) {
        //uncomment below and update the code to test getLehrerKatalogRechtsverhaeltnis
        //instance.getLehrerKatalogRechtsverhaeltnis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLehrerKatalogZugangsgrund', function() {
      it('should call getLehrerKatalogZugangsgrund successfully', function(done) {
        //uncomment below and update the code to test getLehrerKatalogZugangsgrund
        //instance.getLehrerKatalogZugangsgrund(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLehrerListe', function() {
      it('should call getLehrerListe successfully', function(done) {
        //uncomment below and update the code to test getLehrerListe
        //instance.getLehrerListe(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLehrerPersonaldaten', function() {
      it('should call getLehrerPersonaldaten successfully', function(done) {
        //uncomment below and update the code to test getLehrerPersonaldaten
        //instance.getLehrerPersonaldaten(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLehrerStammdaten', function() {
      it('should call getLehrerStammdaten successfully', function(done) {
        //uncomment below and update the code to test getLehrerStammdaten
        //instance.getLehrerStammdaten(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerAbgangsdatum', function() {
      it('should call setLehrerAbgangsdatum successfully', function(done) {
        //uncomment below and update the code to test setLehrerAbgangsdatum
        //instance.setLehrerAbgangsdatum(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerAbgangsgrund', function() {
      it('should call setLehrerAbgangsgrund successfully', function(done) {
        //uncomment below and update the code to test setLehrerAbgangsgrund
        //instance.setLehrerAbgangsgrund(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerAmtsbezeichnung', function() {
      it('should call setLehrerAmtsbezeichnung successfully', function(done) {
        //uncomment below and update the code to test setLehrerAmtsbezeichnung
        //instance.setLehrerAmtsbezeichnung(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerAnrede', function() {
      it('should call setLehrerAnrede successfully', function(done) {
        //uncomment below and update the code to test setLehrerAnrede
        //instance.setLehrerAnrede(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerBeschaeftigungsart', function() {
      it('should call setLehrerBeschaeftigungsart successfully', function(done) {
        //uncomment below and update the code to test setLehrerBeschaeftigungsart
        //instance.setLehrerBeschaeftigungsart(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerEinsatzstatus', function() {
      it('should call setLehrerEinsatzstatus successfully', function(done) {
        //uncomment below and update the code to test setLehrerEinsatzstatus
        //instance.setLehrerEinsatzstatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerEmailDienstlich', function() {
      it('should call setLehrerEmailDienstlich successfully', function(done) {
        //uncomment below and update the code to test setLehrerEmailDienstlich
        //instance.setLehrerEmailDienstlich(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerEmailPrivat', function() {
      it('should call setLehrerEmailPrivat successfully', function(done) {
        //uncomment below and update the code to test setLehrerEmailPrivat
        //instance.setLehrerEmailPrivat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerFoto', function() {
      it('should call setLehrerFoto successfully', function(done) {
        //uncomment below and update the code to test setLehrerFoto
        //instance.setLehrerFoto(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerGeburtsdatum', function() {
      it('should call setLehrerGeburtsdatum successfully', function(done) {
        //uncomment below and update the code to test setLehrerGeburtsdatum
        //instance.setLehrerGeburtsdatum(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerGeschlecht', function() {
      it('should call setLehrerGeschlecht successfully', function(done) {
        //uncomment below and update the code to test setLehrerGeschlecht
        //instance.setLehrerGeschlecht(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerIdentNrTeil1', function() {
      it('should call setLehrerIdentNrTeil1 successfully', function(done) {
        //uncomment below and update the code to test setLehrerIdentNrTeil1
        //instance.setLehrerIdentNrTeil1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerIdentNrTeil2SerNr', function() {
      it('should call setLehrerIdentNrTeil2SerNr successfully', function(done) {
        //uncomment below and update the code to test setLehrerIdentNrTeil2SerNr
        //instance.setLehrerIdentNrTeil2SerNr(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerKuerzel', function() {
      it('should call setLehrerKuerzel successfully', function(done) {
        //uncomment below and update the code to test setLehrerKuerzel
        //instance.setLehrerKuerzel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerLbvPersonalnummer', function() {
      it('should call setLehrerLbvPersonalnummer successfully', function(done) {
        //uncomment below and update the code to test setLehrerLbvPersonalnummer
        //instance.setLehrerLbvPersonalnummer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerLbvVerguetungsschluessel', function() {
      it('should call setLehrerLbvVerguetungsschluessel successfully', function(done) {
        //uncomment below and update the code to test setLehrerLbvVerguetungsschluessel
        //instance.setLehrerLbvVerguetungsschluessel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerLeitungsfunktion', function() {
      it('should call setLehrerLeitungsfunktion successfully', function(done) {
        //uncomment below and update the code to test setLehrerLeitungsfunktion
        //instance.setLehrerLeitungsfunktion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerMasernImpfnachweis', function() {
      it('should call setLehrerMasernImpfnachweis successfully', function(done) {
        //uncomment below and update the code to test setLehrerMasernImpfnachweis
        //instance.setLehrerMasernImpfnachweis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerNachname', function() {
      it('should call setLehrerNachname successfully', function(done) {
        //uncomment below and update the code to test setLehrerNachname
        //instance.setLehrerNachname(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerOrtsteilID', function() {
      it('should call setLehrerOrtsteilID successfully', function(done) {
        //uncomment below and update the code to test setLehrerOrtsteilID
        //instance.setLehrerOrtsteilID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerPersonalTyp', function() {
      it('should call setLehrerPersonalTyp successfully', function(done) {
        //uncomment below and update the code to test setLehrerPersonalTyp
        //instance.setLehrerPersonalTyp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerPersonalaktennummer', function() {
      it('should call setLehrerPersonalaktennummer successfully', function(done) {
        //uncomment below and update the code to test setLehrerPersonalaktennummer
        //instance.setLehrerPersonalaktennummer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerPflichtstundensoll', function() {
      it('should call setLehrerPflichtstundensoll successfully', function(done) {
        //uncomment below and update the code to test setLehrerPflichtstundensoll
        //instance.setLehrerPflichtstundensoll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerRechtsverhaeltnis', function() {
      it('should call setLehrerRechtsverhaeltnis successfully', function(done) {
        //uncomment below and update the code to test setLehrerRechtsverhaeltnis
        //instance.setLehrerRechtsverhaeltnis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerStaatsangehoerigkeitID', function() {
      it('should call setLehrerStaatsangehoerigkeitID successfully', function(done) {
        //uncomment below and update the code to test setLehrerStaatsangehoerigkeitID
        //instance.setLehrerStaatsangehoerigkeitID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerStammschulnummer', function() {
      it('should call setLehrerStammschulnummer successfully', function(done) {
        //uncomment below and update the code to test setLehrerStammschulnummer
        //instance.setLehrerStammschulnummer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerStrasse', function() {
      it('should call setLehrerStrasse successfully', function(done) {
        //uncomment below and update the code to test setLehrerStrasse
        //instance.setLehrerStrasse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerTelefon', function() {
      it('should call setLehrerTelefon successfully', function(done) {
        //uncomment below and update the code to test setLehrerTelefon
        //instance.setLehrerTelefon(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerTelefonMobil', function() {
      it('should call setLehrerTelefonMobil successfully', function(done) {
        //uncomment below and update the code to test setLehrerTelefonMobil
        //instance.setLehrerTelefonMobil(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerTitel', function() {
      it('should call setLehrerTitel successfully', function(done) {
        //uncomment below and update the code to test setLehrerTitel
        //instance.setLehrerTitel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerVorname', function() {
      it('should call setLehrerVorname successfully', function(done) {
        //uncomment below and update the code to test setLehrerVorname
        //instance.setLehrerVorname(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerWohnortID', function() {
      it('should call setLehrerWohnortID successfully', function(done) {
        //uncomment below and update the code to test setLehrerWohnortID
        //instance.setLehrerWohnortID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerZugangsdatum', function() {
      it('should call setLehrerZugangsdatum successfully', function(done) {
        //uncomment below and update the code to test setLehrerZugangsdatum
        //instance.setLehrerZugangsdatum(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setLehrerZugangsgrund', function() {
      it('should call setLehrerZugangsgrund successfully', function(done) {
        //uncomment below and update the code to test setLehrerZugangsgrund
        //instance.setLehrerZugangsgrund(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
