/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.SchuelerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SchuelerApi', function() {
    describe('getSchuelerKatalogFahrschuelerart', function() {
      it('should call getSchuelerKatalogFahrschuelerart successfully', function(done) {
        //uncomment below and update the code to test getSchuelerKatalogFahrschuelerart
        //instance.getSchuelerKatalogFahrschuelerart(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSchuelerKatalogFoerderschwerpunkt', function() {
      it('should call getSchuelerKatalogFoerderschwerpunkt successfully', function(done) {
        //uncomment below and update the code to test getSchuelerKatalogFoerderschwerpunkt
        //instance.getSchuelerKatalogFoerderschwerpunkt(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSchuelerListe', function() {
      it('should call getSchuelerListe successfully', function(done) {
        //uncomment below and update the code to test getSchuelerListe
        //instance.getSchuelerListe(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSchuelerStammdaten', function() {
      it('should call getSchuelerStammdaten successfully', function(done) {
        //uncomment below and update the code to test getSchuelerStammdaten
        //instance.getSchuelerStammdaten(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerAlleVornamen', function() {
      it('should call setSchuelerAlleVornamen successfully', function(done) {
        //uncomment below and update the code to test setSchuelerAlleVornamen
        //instance.setSchuelerAlleVornamen(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerAnmeldedatum', function() {
      it('should call setSchuelerAnmeldedatum successfully', function(done) {
        //uncomment below and update the code to test setSchuelerAnmeldedatum
        //instance.setSchuelerAnmeldedatum(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerAufnahmedatum', function() {
      it('should call setSchuelerAufnahmedatum successfully', function(done) {
        //uncomment below and update the code to test setSchuelerAufnahmedatum
        //instance.setSchuelerAufnahmedatum(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerBemerkungen', function() {
      it('should call setSchuelerBemerkungen successfully', function(done) {
        //uncomment below and update the code to test setSchuelerBemerkungen
        //instance.setSchuelerBemerkungen(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerDruckeKonfessionAufZeugnisse', function() {
      it('should call setSchuelerDruckeKonfessionAufZeugnisse successfully', function(done) {
        //uncomment below and update the code to test setSchuelerDruckeKonfessionAufZeugnisse
        //instance.setSchuelerDruckeKonfessionAufZeugnisse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerEmailPrivat', function() {
      it('should call setSchuelerEmailPrivat successfully', function(done) {
        //uncomment below and update the code to test setSchuelerEmailPrivat
        //instance.setSchuelerEmailPrivat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerEmailSchule', function() {
      it('should call setSchuelerEmailSchule successfully', function(done) {
        //uncomment below and update the code to test setSchuelerEmailSchule
        //instance.setSchuelerEmailSchule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerErhaeltMeisterBAFOEG', function() {
      it('should call setSchuelerErhaeltMeisterBAFOEG successfully', function(done) {
        //uncomment below and update the code to test setSchuelerErhaeltMeisterBAFOEG
        //instance.setSchuelerErhaeltMeisterBAFOEG(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerErhaeltSchuelerBAFOEG', function() {
      it('should call setSchuelerErhaeltSchuelerBAFOEG successfully', function(done) {
        //uncomment below and update the code to test setSchuelerErhaeltSchuelerBAFOEG
        //instance.setSchuelerErhaeltSchuelerBAFOEG(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerFahrschuelerArtID', function() {
      it('should call setSchuelerFahrschuelerArtID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerFahrschuelerArtID
        //instance.setSchuelerFahrschuelerArtID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerFoerderschwerpunkt2ID', function() {
      it('should call setSchuelerFoerderschwerpunkt2ID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerFoerderschwerpunkt2ID
        //instance.setSchuelerFoerderschwerpunkt2ID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerFoerderschwerpunktID', function() {
      it('should call setSchuelerFoerderschwerpunktID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerFoerderschwerpunktID
        //instance.setSchuelerFoerderschwerpunktID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerFoto', function() {
      it('should call setSchuelerFoto successfully', function(done) {
        //uncomment below and update the code to test setSchuelerFoto
        //instance.setSchuelerFoto(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerGeburtsdatum', function() {
      it('should call setSchuelerGeburtsdatum successfully', function(done) {
        //uncomment below and update the code to test setSchuelerGeburtsdatum
        //instance.setSchuelerGeburtsdatum(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerGeburtsland', function() {
      it('should call setSchuelerGeburtsland successfully', function(done) {
        //uncomment below and update the code to test setSchuelerGeburtsland
        //instance.setSchuelerGeburtsland(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerGeburtslandMutter', function() {
      it('should call setSchuelerGeburtslandMutter successfully', function(done) {
        //uncomment below and update the code to test setSchuelerGeburtslandMutter
        //instance.setSchuelerGeburtslandMutter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerGeburtslandVater', function() {
      it('should call setSchuelerGeburtslandVater successfully', function(done) {
        //uncomment below and update the code to test setSchuelerGeburtslandVater
        //instance.setSchuelerGeburtslandVater(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerGeburtsname', function() {
      it('should call setSchuelerGeburtsname successfully', function(done) {
        //uncomment below and update the code to test setSchuelerGeburtsname
        //instance.setSchuelerGeburtsname(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerGeburtsort', function() {
      it('should call setSchuelerGeburtsort successfully', function(done) {
        //uncomment below and update the code to test setSchuelerGeburtsort
        //instance.setSchuelerGeburtsort(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerGeschlecht', function() {
      it('should call setSchuelerGeschlecht successfully', function(done) {
        //uncomment below and update the code to test setSchuelerGeschlecht
        //instance.setSchuelerGeschlecht(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerHaltestelleID', function() {
      it('should call setSchuelerHaltestelleID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerHaltestelleID
        //instance.setSchuelerHaltestelleID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerHatMasernimpfnachweis', function() {
      it('should call setSchuelerHatMasernimpfnachweis successfully', function(done) {
        //uncomment below and update the code to test setSchuelerHatMasernimpfnachweis
        //instance.setSchuelerHatMasernimpfnachweis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerHatMigrationshintergrund', function() {
      it('should call setSchuelerHatMigrationshintergrund successfully', function(done) {
        //uncomment below and update the code to test setSchuelerHatMigrationshintergrund
        //instance.setSchuelerHatMigrationshintergrund(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerIstAOSF', function() {
      it('should call setSchuelerIstAOSF successfully', function(done) {
        //uncomment below and update the code to test setSchuelerIstAOSF
        //instance.setSchuelerIstAOSF(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerIstBerufsschulpflichtErfuellt', function() {
      it('should call setSchuelerIstBerufsschulpflichtErfuellt successfully', function(done) {
        //uncomment below and update the code to test setSchuelerIstBerufsschulpflichtErfuellt
        //instance.setSchuelerIstBerufsschulpflichtErfuellt(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerIstDuplikat', function() {
      it('should call setSchuelerIstDuplikat successfully', function(done) {
        //uncomment below and update the code to test setSchuelerIstDuplikat
        //instance.setSchuelerIstDuplikat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerIstLernenZieldifferent', function() {
      it('should call setSchuelerIstLernenZieldifferent successfully', function(done) {
        //uncomment below and update the code to test setSchuelerIstLernenZieldifferent
        //instance.setSchuelerIstLernenZieldifferent(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerIstSchulpflichtErfuellt', function() {
      it('should call setSchuelerIstSchulpflichtErfuellt successfully', function(done) {
        //uncomment below and update the code to test setSchuelerIstSchulpflichtErfuellt
        //instance.setSchuelerIstSchulpflichtErfuellt(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerIstVolljaehrig', function() {
      it('should call setSchuelerIstVolljaehrig successfully', function(done) {
        //uncomment below and update the code to test setSchuelerIstVolljaehrig
        //instance.setSchuelerIstVolljaehrig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerKeineAuskunftAnDritte', function() {
      it('should call setSchuelerKeineAuskunftAnDritte successfully', function(done) {
        //uncomment below and update the code to test setSchuelerKeineAuskunftAnDritte
        //instance.setSchuelerKeineAuskunftAnDritte(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerNachname', function() {
      it('should call setSchuelerNachname successfully', function(done) {
        //uncomment below and update the code to test setSchuelerNachname
        //instance.setSchuelerNachname(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerOrtsteilID', function() {
      it('should call setSchuelerOrtsteilID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerOrtsteilID
        //instance.setSchuelerOrtsteilID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerReligionID', function() {
      it('should call setSchuelerReligionID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerReligionID
        //instance.setSchuelerReligionID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerReligionabmeldung', function() {
      it('should call setSchuelerReligionabmeldung successfully', function(done) {
        //uncomment below and update the code to test setSchuelerReligionabmeldung
        //instance.setSchuelerReligionabmeldung(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerReligionanmeldung', function() {
      it('should call setSchuelerReligionanmeldung successfully', function(done) {
        //uncomment below and update the code to test setSchuelerReligionanmeldung
        //instance.setSchuelerReligionanmeldung(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerStaatsangehoerigkeit2ID', function() {
      it('should call setSchuelerStaatsangehoerigkeit2ID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerStaatsangehoerigkeit2ID
        //instance.setSchuelerStaatsangehoerigkeit2ID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerStaatsangehoerigkeitID', function() {
      it('should call setSchuelerStaatsangehoerigkeitID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerStaatsangehoerigkeitID
        //instance.setSchuelerStaatsangehoerigkeitID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerStatus', function() {
      it('should call setSchuelerStatus successfully', function(done) {
        //uncomment below and update the code to test setSchuelerStatus
        //instance.setSchuelerStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerStrasse', function() {
      it('should call setSchuelerStrasse successfully', function(done) {
        //uncomment below and update the code to test setSchuelerStrasse
        //instance.setSchuelerStrasse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerTelefon', function() {
      it('should call setSchuelerTelefon successfully', function(done) {
        //uncomment below and update the code to test setSchuelerTelefon
        //instance.setSchuelerTelefon(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerTelefonMobil', function() {
      it('should call setSchuelerTelefonMobil successfully', function(done) {
        //uncomment below and update the code to test setSchuelerTelefonMobil
        //instance.setSchuelerTelefonMobil(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerVerkehrspracheFamilie', function() {
      it('should call setSchuelerVerkehrspracheFamilie successfully', function(done) {
        //uncomment below and update the code to test setSchuelerVerkehrspracheFamilie
        //instance.setSchuelerVerkehrspracheFamilie(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerVorname', function() {
      it('should call setSchuelerVorname successfully', function(done) {
        //uncomment below and update the code to test setSchuelerVorname
        //instance.setSchuelerVorname(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerWohnortID', function() {
      it('should call setSchuelerWohnortID successfully', function(done) {
        //uncomment below and update the code to test setSchuelerWohnortID
        //instance.setSchuelerWohnortID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerZusatzNachname', function() {
      it('should call setSchuelerZusatzNachname successfully', function(done) {
        //uncomment below and update the code to test setSchuelerZusatzNachname
        //instance.setSchuelerZusatzNachname(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setSchuelerZuzugsjahr', function() {
      it('should call setSchuelerZuzugsjahr successfully', function(done) {
        //uncomment below and update the code to test setSchuelerZuzugsjahr
        //instance.setSchuelerZuzugsjahr(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
