/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Abiturdaten from '../model/Abiturdaten';
import BelegpruefungErgebnis from '../model/BelegpruefungErgebnis';

/**
* AbschlussGOSt service.
* @module api/AbschlussGOStApi
* @version 1.0.0
*/
export default class AbschlussGOStApi {

    /**
    * Constructs a new AbschlussGOStApi. 
    * @alias module:api/AbschlussGOStApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Führt eine Belegprüfung nur für die EF.1 anhand der übergebenen Abiturdaten durch.
     * Prüft anhand der übergeben Abiturdaten, ob die Belegung in den Abiturdaten korrekt ist oder nicht. Es werden ggf. auch Belegungsfehler und Hinweise zur Belegung zurückgegeben.
     * @param {module:model/Abiturdaten} abiturdaten Die Abiturdaten für die Belegprüfung
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BelegpruefungErgebnis} and HTTP response
     */
    getBelegpruefungEF1WithHttpInfo(abiturdaten) {
      let postBody = abiturdaten;
      // verify the required parameter 'abiturdaten' is set
      if (abiturdaten === undefined || abiturdaten === null) {
        throw new Error("Missing the required parameter 'abiturdaten' when calling getBelegpruefungEF1");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BelegpruefungErgebnis;
      return this.apiClient.callApi(
        '/api/abschluss/gost/belegpruefungEF1', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Führt eine Belegprüfung nur für die EF.1 anhand der übergebenen Abiturdaten durch.
     * Prüft anhand der übergeben Abiturdaten, ob die Belegung in den Abiturdaten korrekt ist oder nicht. Es werden ggf. auch Belegungsfehler und Hinweise zur Belegung zurückgegeben.
     * @param {module:model/Abiturdaten} abiturdaten Die Abiturdaten für die Belegprüfung
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BelegpruefungErgebnis}
     */
    getBelegpruefungEF1(abiturdaten) {
      return this.getBelegpruefungEF1WithHttpInfo(abiturdaten)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Führt eine Belegprüfung anhand der übergebenen Abiturdaten durch.
     * Prüft anhand der übergeben Abiturdaten, ob die Belegung in den Abiturdaten korrekt ist oder nicht. Es werden ggf. auch Belegungsfehler und Hinweise zur Belegung zurückgegeben.
     * @param {module:model/Abiturdaten} abiturdaten Die Abiturdaten für die Belegprüfung
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BelegpruefungErgebnis} and HTTP response
     */
    getBelegpruefungGesamtWithHttpInfo(abiturdaten) {
      let postBody = abiturdaten;
      // verify the required parameter 'abiturdaten' is set
      if (abiturdaten === undefined || abiturdaten === null) {
        throw new Error("Missing the required parameter 'abiturdaten' when calling getBelegpruefungGesamt");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BelegpruefungErgebnis;
      return this.apiClient.callApi(
        '/api/abschluss/gost/belegpruefung', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Führt eine Belegprüfung anhand der übergebenen Abiturdaten durch.
     * Prüft anhand der übergeben Abiturdaten, ob die Belegung in den Abiturdaten korrekt ist oder nicht. Es werden ggf. auch Belegungsfehler und Hinweise zur Belegung zurückgegeben.
     * @param {module:model/Abiturdaten} abiturdaten Die Abiturdaten für die Belegprüfung
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BelegpruefungErgebnis}
     */
    getBelegpruefungGesamt(abiturdaten) {
      return this.getBelegpruefungGesamtWithHttpInfo(abiturdaten)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
