/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AbschlussFach model module.
 * @module model/AbschlussFach
 * @version 1.0.0
 */
class AbschlussFach {
    /**
     * Constructs a new <code>AbschlussFach</code>.
     * die Fachinformationen eines Faches für die Abschlussberechnung.
     * @alias module:model/AbschlussFach
     * @param kuerzel {String} Das Kürzel des Faches
     * @param note {Number} Die Note in dem Fach
     * @param kursart {module:model/AbschlussFach.KursartEnum} Die Kursart des Faches
     */
    constructor(kuerzel, note, kursart) { 
        
        AbschlussFach.initialize(this, kuerzel, note, kursart);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, kuerzel, note, kursart) { 
        obj['kuerzel'] = kuerzel;
        obj['note'] = note;
        obj['kursart'] = kursart;
    }

    /**
     * Constructs a <code>AbschlussFach</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AbschlussFach} obj Optional instance to populate.
     * @return {module:model/AbschlussFach} The populated <code>AbschlussFach</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AbschlussFach();

            if (data.hasOwnProperty('kuerzel')) {
                obj['kuerzel'] = ApiClient.convertToType(data['kuerzel'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'Number');
            }
            if (data.hasOwnProperty('kursart')) {
                obj['kursart'] = ApiClient.convertToType(data['kursart'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Das Kürzel des Faches
 * @member {String} kuerzel
 */
AbschlussFach.prototype['kuerzel'] = undefined;

/**
 * Die Note in dem Fach
 * @member {Number} note
 */
AbschlussFach.prototype['note'] = undefined;

/**
 * Die Kursart des Faches
 * @member {module:model/AbschlussFach.KursartEnum} kursart
 */
AbschlussFach.prototype['kursart'] = undefined;





/**
 * Allowed values for the <code>kursart</code> property.
 * @enum {String}
 * @readonly
 */
AbschlussFach['KursartEnum'] = {

    /**
     * value: "E"
     * @const
     */
    "E": "E",

    /**
     * value: "G"
     * @const
     */
    "G": "G",

    /**
     * value: ""
     * @const
     */
    "empty": ""
};



export default AbschlussFach;

