/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AbschlussFach from './AbschlussFach';

/**
 * The AbschlussFaecher model module.
 * @module model/AbschlussFaecher
 * @version 1.0.0
 */
class AbschlussFaecher {
    /**
     * Constructs a new <code>AbschlussFaecher</code>.
     * Die Fachinformationen für eine Abschlussberechnung
     * @alias module:model/AbschlussFaecher
     * @param jahrgang {String} Der Jahrgang für den die Abschlussberechnung erstellt werden soll, im allgemeinen 10 - alles andere wird als voriger Jahrgang gewertet
     * @param faecher {Array.<module:model/AbschlussFach>} Die Fachinformationen
     */
    constructor(jahrgang, faecher) { 
        
        AbschlussFaecher.initialize(this, jahrgang, faecher);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jahrgang, faecher) { 
        obj['jahrgang'] = jahrgang;
        obj['faecher'] = faecher;
    }

    /**
     * Constructs a <code>AbschlussFaecher</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AbschlussFaecher} obj Optional instance to populate.
     * @return {module:model/AbschlussFaecher} The populated <code>AbschlussFaecher</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AbschlussFaecher();

            if (data.hasOwnProperty('jahrgang')) {
                obj['jahrgang'] = ApiClient.convertToType(data['jahrgang'], 'String');
            }
            if (data.hasOwnProperty('faecher')) {
                obj['faecher'] = ApiClient.convertToType(data['faecher'], [AbschlussFach]);
            }
        }
        return obj;
    }


}

/**
 * Der Jahrgang für den die Abschlussberechnung erstellt werden soll, im allgemeinen 10 - alles andere wird als voriger Jahrgang gewertet
 * @member {String} jahrgang
 */
AbschlussFaecher.prototype['jahrgang'] = undefined;

/**
 * Die Fachinformationen
 * @member {Array.<module:model/AbschlussFach>} faecher
 */
AbschlussFaecher.prototype['faecher'] = undefined;






export default AbschlussFaecher;

