/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClientKonfiguration model module.
 * @module model/ClientKonfiguration
 * @version 1.0.0
 */
class ClientKonfiguration {
    /**
     * Constructs a new <code>ClientKonfiguration</code>.
     * Das Key-Value-Paar eines Konfigurationseintrags für den Client.
     * @alias module:model/ClientKonfiguration
     * @param key {String} der Schlüsselname des Konfigurationseintrags
     * @param value {String} der Wert des Konfigurationseintrags
     */
    constructor(key, value) { 
        
        ClientKonfiguration.initialize(this, key, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, value) { 
        obj['key'] = key;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>ClientKonfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientKonfiguration} obj Optional instance to populate.
     * @return {module:model/ClientKonfiguration} The populated <code>ClientKonfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientKonfiguration();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * der Schlüsselname des Konfigurationseintrags
 * @member {String} key
 */
ClientKonfiguration.prototype['key'] = undefined;

/**
 * der Wert des Konfigurationseintrags
 * @member {String} value
 */
ClientKonfiguration.prototype['value'] = undefined;






export default ClientKonfiguration;

