/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FaecherlisteEintrag model module.
 * @module model/FaecherlisteEintrag
 * @version 1.0.0
 */
class FaecherlisteEintrag {
    /**
     * Constructs a new <code>FaecherlisteEintrag</code>.
     * ein Eintrag eines Faches in der Fächerliste.
     * @alias module:model/FaecherlisteEintrag
     * @param id {Number} die ID des Faches
     * @param kuerzel {String} das Kürzel des Faches
     * @param kuerzelStatistik {String} das dem Fach zugeordnete Statistik-Kürzel
     * @param bezeichnung {String} der Name / die Bezeichnung des Faches
     * @param sortierung {Number} die Sortierreihenfolge des Fächerlisten-Eintrags
     * @param istOberstufenFach {Boolean} gibt an, ob es sich um ein Fach der Oberstufe handelt oder nicht.
     * @param istSichtbar {Boolean} gibt an, ob der Eintrag in der Anwendung sichtbar sein soll oder nicht.
     * @param istAenderbar {Boolean} gibt an, ob der Eintrag in der Anwendung änderbar sein soll oder nicht.
     */
    constructor(id, kuerzel, kuerzelStatistik, bezeichnung, sortierung, istOberstufenFach, istSichtbar, istAenderbar) { 
        
        FaecherlisteEintrag.initialize(this, id, kuerzel, kuerzelStatistik, bezeichnung, sortierung, istOberstufenFach, istSichtbar, istAenderbar);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, kuerzel, kuerzelStatistik, bezeichnung, sortierung, istOberstufenFach, istSichtbar, istAenderbar) { 
        obj['id'] = id;
        obj['kuerzel'] = kuerzel;
        obj['kuerzelStatistik'] = kuerzelStatistik;
        obj['bezeichnung'] = bezeichnung;
        obj['sortierung'] = sortierung;
        obj['istOberstufenFach'] = istOberstufenFach;
        obj['istSichtbar'] = istSichtbar;
        obj['istAenderbar'] = istAenderbar;
    }

    /**
     * Constructs a <code>FaecherlisteEintrag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FaecherlisteEintrag} obj Optional instance to populate.
     * @return {module:model/FaecherlisteEintrag} The populated <code>FaecherlisteEintrag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FaecherlisteEintrag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('kuerzel')) {
                obj['kuerzel'] = ApiClient.convertToType(data['kuerzel'], 'String');
            }
            if (data.hasOwnProperty('kuerzelStatistik')) {
                obj['kuerzelStatistik'] = ApiClient.convertToType(data['kuerzelStatistik'], 'String');
            }
            if (data.hasOwnProperty('bezeichnung')) {
                obj['bezeichnung'] = ApiClient.convertToType(data['bezeichnung'], 'String');
            }
            if (data.hasOwnProperty('sortierung')) {
                obj['sortierung'] = ApiClient.convertToType(data['sortierung'], 'Number');
            }
            if (data.hasOwnProperty('istOberstufenFach')) {
                obj['istOberstufenFach'] = ApiClient.convertToType(data['istOberstufenFach'], 'Boolean');
            }
            if (data.hasOwnProperty('istSichtbar')) {
                obj['istSichtbar'] = ApiClient.convertToType(data['istSichtbar'], 'Boolean');
            }
            if (data.hasOwnProperty('istAenderbar')) {
                obj['istAenderbar'] = ApiClient.convertToType(data['istAenderbar'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * die ID des Faches
 * @member {Number} id
 */
FaecherlisteEintrag.prototype['id'] = undefined;

/**
 * das Kürzel des Faches
 * @member {String} kuerzel
 */
FaecherlisteEintrag.prototype['kuerzel'] = undefined;

/**
 * das dem Fach zugeordnete Statistik-Kürzel
 * @member {String} kuerzelStatistik
 */
FaecherlisteEintrag.prototype['kuerzelStatistik'] = undefined;

/**
 * der Name / die Bezeichnung des Faches
 * @member {String} bezeichnung
 */
FaecherlisteEintrag.prototype['bezeichnung'] = undefined;

/**
 * die Sortierreihenfolge des Fächerlisten-Eintrags
 * @member {Number} sortierung
 */
FaecherlisteEintrag.prototype['sortierung'] = undefined;

/**
 * gibt an, ob es sich um ein Fach der Oberstufe handelt oder nicht.
 * @member {Boolean} istOberstufenFach
 */
FaecherlisteEintrag.prototype['istOberstufenFach'] = undefined;

/**
 * gibt an, ob der Eintrag in der Anwendung sichtbar sein soll oder nicht.
 * @member {Boolean} istSichtbar
 */
FaecherlisteEintrag.prototype['istSichtbar'] = undefined;

/**
 * gibt an, ob der Eintrag in der Anwendung änderbar sein soll oder nicht.
 * @member {Boolean} istAenderbar
 */
FaecherlisteEintrag.prototype['istAenderbar'] = undefined;






export default FaecherlisteEintrag;

