/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GOStFach model module.
 * @module model/GOStFach
 * @version 1.0.0
 */
class GOStFach {
    /**
     * Constructs a new <code>GOStFach</code>.
     * @alias module:model/GOStFach
     */
    constructor() { 
        
        GOStFach.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GOStFach</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GOStFach} obj Optional instance to populate.
     * @return {module:model/GOStFach} The populated <code>GOStFach</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GOStFach();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('kuerzel')) {
                obj['kuerzel'] = ApiClient.convertToType(data['kuerzel'], 'String');
            }
            if (data.hasOwnProperty('kuerzelAnzeige')) {
                obj['kuerzelAnzeige'] = ApiClient.convertToType(data['kuerzelAnzeige'], 'String');
            }
            if (data.hasOwnProperty('sortierung')) {
                obj['sortierung'] = ApiClient.convertToType(data['sortierung'], 'Number');
            }
            if (data.hasOwnProperty('istFremdsprache')) {
                obj['istFremdsprache'] = ApiClient.convertToType(data['istFremdsprache'], 'Boolean');
            }
            if (data.hasOwnProperty('istFremdSpracheNeuEinsetzendMoeglich')) {
                obj['istFremdSpracheNeuEinsetzendMoeglich'] = ApiClient.convertToType(data['istFremdSpracheNeuEinsetzendMoeglich'], 'Boolean');
            }
            if (data.hasOwnProperty('biliSprache')) {
                obj['biliSprache'] = ApiClient.convertToType(data['biliSprache'], 'String');
            }
            if (data.hasOwnProperty('istMoeglichAbiLK')) {
                obj['istMoeglichAbiLK'] = ApiClient.convertToType(data['istMoeglichAbiLK'], 'Boolean');
            }
            if (data.hasOwnProperty('istMoeglichAbiGKMoeglich')) {
                obj['istMoeglichAbiGKMoeglich'] = ApiClient.convertToType(data['istMoeglichAbiGKMoeglich'], 'Boolean');
            }
            if (data.hasOwnProperty('istMoeglichEF1')) {
                obj['istMoeglichEF1'] = ApiClient.convertToType(data['istMoeglichEF1'], 'Boolean');
            }
            if (data.hasOwnProperty('istMoeglichEF2')) {
                obj['istMoeglichEF2'] = ApiClient.convertToType(data['istMoeglichEF2'], 'Boolean');
            }
            if (data.hasOwnProperty('istMoeglichQ11')) {
                obj['istMoeglichQ11'] = ApiClient.convertToType(data['istMoeglichQ11'], 'Boolean');
            }
            if (data.hasOwnProperty('istMoeglichQ12')) {
                obj['istMoeglichQ12'] = ApiClient.convertToType(data['istMoeglichQ12'], 'Boolean');
            }
            if (data.hasOwnProperty('istMoeglichQ21')) {
                obj['istMoeglichQ21'] = ApiClient.convertToType(data['istMoeglichQ21'], 'Boolean');
            }
            if (data.hasOwnProperty('istMoeglichQ22')) {
                obj['istMoeglichQ22'] = ApiClient.convertToType(data['istMoeglichQ22'], 'Boolean');
            }
            if (data.hasOwnProperty('wochenstundenEF1')) {
                obj['wochenstundenEF1'] = ApiClient.convertToType(data['wochenstundenEF1'], 'Number');
            }
            if (data.hasOwnProperty('wochenstundenEF2')) {
                obj['wochenstundenEF2'] = ApiClient.convertToType(data['wochenstundenEF2'], 'Number');
            }
            if (data.hasOwnProperty('wochenstundenQualifikationsphase')) {
                obj['wochenstundenQualifikationsphase'] = ApiClient.convertToType(data['wochenstundenQualifikationsphase'], 'Number');
            }
            if (data.hasOwnProperty('mussSchriftlichEF1')) {
                obj['mussSchriftlichEF1'] = ApiClient.convertToType(data['mussSchriftlichEF1'], 'Boolean');
            }
            if (data.hasOwnProperty('mussSchriftlichEF2')) {
                obj['mussSchriftlichEF2'] = ApiClient.convertToType(data['mussSchriftlichEF2'], 'Boolean');
            }
            if (data.hasOwnProperty('projektKursLeitfach1ID')) {
                obj['projektKursLeitfach1ID'] = ApiClient.convertToType(data['projektKursLeitfach1ID'], 'Number');
            }
            if (data.hasOwnProperty('projektKursLeitfach1Kuerzel')) {
                obj['projektKursLeitfach1Kuerzel'] = ApiClient.convertToType(data['projektKursLeitfach1Kuerzel'], 'String');
            }
            if (data.hasOwnProperty('projektKursLeitfach2ID')) {
                obj['projektKursLeitfach2ID'] = ApiClient.convertToType(data['projektKursLeitfach2ID'], 'Number');
            }
            if (data.hasOwnProperty('projektKursLeitfach2Kuerzel')) {
                obj['projektKursLeitfach2Kuerzel'] = ApiClient.convertToType(data['projektKursLeitfach2Kuerzel'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GOStFach.prototype['id'] = undefined;

/**
 * @member {String} kuerzel
 */
GOStFach.prototype['kuerzel'] = undefined;

/**
 * @member {String} kuerzelAnzeige
 */
GOStFach.prototype['kuerzelAnzeige'] = undefined;

/**
 * @member {Number} sortierung
 */
GOStFach.prototype['sortierung'] = undefined;

/**
 * @member {Boolean} istFremdsprache
 */
GOStFach.prototype['istFremdsprache'] = undefined;

/**
 * @member {Boolean} istFremdSpracheNeuEinsetzendMoeglich
 */
GOStFach.prototype['istFremdSpracheNeuEinsetzendMoeglich'] = undefined;

/**
 * @member {String} biliSprache
 */
GOStFach.prototype['biliSprache'] = undefined;

/**
 * @member {Boolean} istMoeglichAbiLK
 */
GOStFach.prototype['istMoeglichAbiLK'] = undefined;

/**
 * @member {Boolean} istMoeglichAbiGKMoeglich
 */
GOStFach.prototype['istMoeglichAbiGKMoeglich'] = undefined;

/**
 * @member {Boolean} istMoeglichEF1
 */
GOStFach.prototype['istMoeglichEF1'] = undefined;

/**
 * @member {Boolean} istMoeglichEF2
 */
GOStFach.prototype['istMoeglichEF2'] = undefined;

/**
 * @member {Boolean} istMoeglichQ11
 */
GOStFach.prototype['istMoeglichQ11'] = undefined;

/**
 * @member {Boolean} istMoeglichQ12
 */
GOStFach.prototype['istMoeglichQ12'] = undefined;

/**
 * @member {Boolean} istMoeglichQ21
 */
GOStFach.prototype['istMoeglichQ21'] = undefined;

/**
 * @member {Boolean} istMoeglichQ22
 */
GOStFach.prototype['istMoeglichQ22'] = undefined;

/**
 * @member {Number} wochenstundenEF1
 */
GOStFach.prototype['wochenstundenEF1'] = undefined;

/**
 * @member {Number} wochenstundenEF2
 */
GOStFach.prototype['wochenstundenEF2'] = undefined;

/**
 * @member {Number} wochenstundenQualifikationsphase
 */
GOStFach.prototype['wochenstundenQualifikationsphase'] = undefined;

/**
 * @member {Boolean} mussSchriftlichEF1
 */
GOStFach.prototype['mussSchriftlichEF1'] = undefined;

/**
 * @member {Boolean} mussSchriftlichEF2
 */
GOStFach.prototype['mussSchriftlichEF2'] = undefined;

/**
 * @member {Number} projektKursLeitfach1ID
 */
GOStFach.prototype['projektKursLeitfach1ID'] = undefined;

/**
 * @member {String} projektKursLeitfach1Kuerzel
 */
GOStFach.prototype['projektKursLeitfach1Kuerzel'] = undefined;

/**
 * @member {Number} projektKursLeitfach2ID
 */
GOStFach.prototype['projektKursLeitfach2ID'] = undefined;

/**
 * @member {String} projektKursLeitfach2Kuerzel
 */
GOStFach.prototype['projektKursLeitfach2Kuerzel'] = undefined;






export default GOStFach;

