/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GOStLeistungenFachbelegung model module.
 * @module model/GOStLeistungenFachbelegung
 * @version 1.0.0
 */
class GOStLeistungenFachbelegung {
    /**
     * Constructs a new <code>GOStLeistungenFachbelegung</code>.
     * @alias module:model/GOStLeistungenFachbelegung
     */
    constructor() { 
        
        GOStLeistungenFachbelegung.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GOStLeistungenFachbelegung</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GOStLeistungenFachbelegung} obj Optional instance to populate.
     * @return {module:model/GOStLeistungenFachbelegung} The populated <code>GOStLeistungenFachbelegung</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GOStLeistungenFachbelegung();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('schuljahr')) {
                obj['schuljahr'] = ApiClient.convertToType(data['schuljahr'], 'Number');
            }
            if (data.hasOwnProperty('halbjahr')) {
                obj['halbjahr'] = ApiClient.convertToType(data['halbjahr'], 'String');
            }
            if (data.hasOwnProperty('abschnitt')) {
                obj['abschnitt'] = ApiClient.convertToType(data['abschnitt'], 'Number');
            }
            if (data.hasOwnProperty('abschnittGewertet')) {
                obj['abschnittGewertet'] = ApiClient.convertToType(data['abschnittGewertet'], 'Boolean');
            }
            if (data.hasOwnProperty('jahrgang')) {
                obj['jahrgang'] = ApiClient.convertToType(data['jahrgang'], 'String');
            }
            if (data.hasOwnProperty('lehrerKuerzel')) {
                obj['lehrerKuerzel'] = ApiClient.convertToType(data['lehrerKuerzel'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('kursart')) {
                obj['kursart'] = ApiClient.convertToType(data['kursart'], 'String');
            }
            if (data.hasOwnProperty('istSchriftlich')) {
                obj['istSchriftlich'] = ApiClient.convertToType(data['istSchriftlich'], 'Boolean');
            }
            if (data.hasOwnProperty('bilingualeSprache')) {
                obj['bilingualeSprache'] = ApiClient.convertToType(data['bilingualeSprache'], 'String');
            }
            if (data.hasOwnProperty('wochenstunden')) {
                obj['wochenstunden'] = ApiClient.convertToType(data['wochenstunden'], 'Number');
            }
            if (data.hasOwnProperty('fehlstundenGesamt')) {
                obj['fehlstundenGesamt'] = ApiClient.convertToType(data['fehlstundenGesamt'], 'Number');
            }
            if (data.hasOwnProperty('fehlstundenUnentschuldigt')) {
                obj['fehlstundenUnentschuldigt'] = ApiClient.convertToType(data['fehlstundenUnentschuldigt'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GOStLeistungenFachbelegung.prototype['id'] = undefined;

/**
 * @member {Number} schuljahr
 */
GOStLeistungenFachbelegung.prototype['schuljahr'] = undefined;

/**
 * @member {module:model/GOStLeistungenFachbelegung.HalbjahrEnum} halbjahr
 */
GOStLeistungenFachbelegung.prototype['halbjahr'] = undefined;

/**
 * @member {Number} abschnitt
 */
GOStLeistungenFachbelegung.prototype['abschnitt'] = undefined;

/**
 * @member {Boolean} abschnittGewertet
 */
GOStLeistungenFachbelegung.prototype['abschnittGewertet'] = undefined;

/**
 * @member {String} jahrgang
 */
GOStLeistungenFachbelegung.prototype['jahrgang'] = undefined;

/**
 * @member {String} lehrerKuerzel
 */
GOStLeistungenFachbelegung.prototype['lehrerKuerzel'] = undefined;

/**
 * @member {module:model/GOStLeistungenFachbelegung.NoteEnum} note
 */
GOStLeistungenFachbelegung.prototype['note'] = undefined;

/**
 * @member {module:model/GOStLeistungenFachbelegung.KursartEnum} kursart
 */
GOStLeistungenFachbelegung.prototype['kursart'] = undefined;

/**
 * @member {Boolean} istSchriftlich
 */
GOStLeistungenFachbelegung.prototype['istSchriftlich'] = undefined;

/**
 * @member {String} bilingualeSprache
 */
GOStLeistungenFachbelegung.prototype['bilingualeSprache'] = undefined;

/**
 * @member {Number} wochenstunden
 */
GOStLeistungenFachbelegung.prototype['wochenstunden'] = undefined;

/**
 * @member {Number} fehlstundenGesamt
 */
GOStLeistungenFachbelegung.prototype['fehlstundenGesamt'] = undefined;

/**
 * @member {Number} fehlstundenUnentschuldigt
 */
GOStLeistungenFachbelegung.prototype['fehlstundenUnentschuldigt'] = undefined;





/**
 * Allowed values for the <code>halbjahr</code> property.
 * @enum {String}
 * @readonly
 */
GOStLeistungenFachbelegung['HalbjahrEnum'] = {

    /**
     * value: "EF1"
     * @const
     */
    "EF1": "EF1",

    /**
     * value: "EF2"
     * @const
     */
    "EF2": "EF2",

    /**
     * value: "Q11"
     * @const
     */
    "Q11": "Q11",

    /**
     * value: "Q12"
     * @const
     */
    "Q12": "Q12",

    /**
     * value: "Q21"
     * @const
     */
    "Q21": "Q21",

    /**
     * value: "Q22"
     * @const
     */
    "Q22": "Q22"
};


/**
 * Allowed values for the <code>note</code> property.
 * @enum {String}
 * @readonly
 */
GOStLeistungenFachbelegung['NoteEnum'] = {

    /**
     * value: "1P"
     * @const
     */
    "1P": "1P",

    /**
     * value: "1"
     * @const
     */
    "1": "1",

    /**
     * value: "1M"
     * @const
     */
    "1M": "1M",

    /**
     * value: "2P"
     * @const
     */
    "2P": "2P",

    /**
     * value: "2"
     * @const
     */
    "2": "2",

    /**
     * value: "2M"
     * @const
     */
    "2M": "2M",

    /**
     * value: "3P"
     * @const
     */
    "3P": "3P",

    /**
     * value: "3"
     * @const
     */
    "3": "3",

    /**
     * value: "3M"
     * @const
     */
    "3M": "3M",

    /**
     * value: "4P"
     * @const
     */
    "4P": "4P",

    /**
     * value: "4"
     * @const
     */
    "4": "4",

    /**
     * value: "4M"
     * @const
     */
    "4M": "4M",

    /**
     * value: "5P"
     * @const
     */
    "5P": "5P",

    /**
     * value: "5"
     * @const
     */
    "5": "5",

    /**
     * value: "5M"
     * @const
     */
    "5M": "5M",

    /**
     * value: "6"
     * @const
     */
    "6": "6",

    /**
     * value: "E1"
     * @const
     */
    "E1": "E1",

    /**
     * value: "E2"
     * @const
     */
    "E2": "E2",

    /**
     * value: "E3"
     * @const
     */
    "E3": "E3",

    /**
     * value: "AT"
     * @const
     */
    "AT": "AT",

    /**
     * value: "AM"
     * @const
     */
    "AM": "AM",

    /**
     * value: "NB"
     * @const
     */
    "NB": "NB",

    /**
     * value: "NT"
     * @const
     */
    "NT": "NT",

    /**
     * value: "NE"
     * @const
     */
    "NE": "NE",

    /**
     * value: "LM"
     * @const
     */
    "LM": "LM",

    /**
     * value: ""
     * @const
     */
    "empty": ""
};


/**
 * Allowed values for the <code>kursart</code> property.
 * @enum {String}
 * @readonly
 */
GOStLeistungenFachbelegung['KursartEnum'] = {

    /**
     * value: "LK"
     * @const
     */
    "LK": "LK",

    /**
     * value: "GK"
     * @const
     */
    "GK": "GK",

    /**
     * value: "ZK"
     * @const
     */
    "ZK": "ZK",

    /**
     * value: "PJK"
     * @const
     */
    "PJK": "PJK",

    /**
     * value: "VTF"
     * @const
     */
    "VTF": "VTF"
};



export default GOStLeistungenFachbelegung;

