/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GOStLeistungenFachwahl from './GOStLeistungenFachwahl';
import Sprachenfolge from './Sprachenfolge';

/**
 * The GOStLeistungen model module.
 * @module model/GOStLeistungen
 * @version 1.0.0
 */
class GOStLeistungen {
    /**
     * Constructs a new <code>GOStLeistungen</code>.
     * @alias module:model/GOStLeistungen
     */
    constructor() { 
        
        GOStLeistungen.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GOStLeistungen</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GOStLeistungen} obj Optional instance to populate.
     * @return {module:model/GOStLeistungen} The populated <code>GOStLeistungen</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GOStLeistungen();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('aktuellesSchuljahr')) {
                obj['aktuellesSchuljahr'] = ApiClient.convertToType(data['aktuellesSchuljahr'], 'Number');
            }
            if (data.hasOwnProperty('aktuellerJahrgang')) {
                obj['aktuellerJahrgang'] = ApiClient.convertToType(data['aktuellerJahrgang'], 'String');
            }
            if (data.hasOwnProperty('sprachenfolge')) {
                obj['sprachenfolge'] = Sprachenfolge.constructFromObject(data['sprachenfolge']);
            }
            if (data.hasOwnProperty('bilingualeSprache')) {
                obj['bilingualeSprache'] = ApiClient.convertToType(data['bilingualeSprache'], 'String');
            }
            if (data.hasOwnProperty('projektkursThema')) {
                obj['projektkursThema'] = ApiClient.convertToType(data['projektkursThema'], 'String');
            }
            if (data.hasOwnProperty('projektkursLeitfach1Kuerzel')) {
                obj['projektkursLeitfach1Kuerzel'] = ApiClient.convertToType(data['projektkursLeitfach1Kuerzel'], 'String');
            }
            if (data.hasOwnProperty('projektkursLeitfach2Kuerzel')) {
                obj['projektkursLeitfach2Kuerzel'] = ApiClient.convertToType(data['projektkursLeitfach2Kuerzel'], 'String');
            }
            if (data.hasOwnProperty('faecher')) {
                obj['faecher'] = ApiClient.convertToType(data['faecher'], [GOStLeistungenFachwahl]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GOStLeistungen.prototype['id'] = undefined;

/**
 * @member {Number} aktuellesSchuljahr
 */
GOStLeistungen.prototype['aktuellesSchuljahr'] = undefined;

/**
 * @member {String} aktuellerJahrgang
 */
GOStLeistungen.prototype['aktuellerJahrgang'] = undefined;

/**
 * @member {module:model/Sprachenfolge} sprachenfolge
 */
GOStLeistungen.prototype['sprachenfolge'] = undefined;

/**
 * @member {String} bilingualeSprache
 */
GOStLeistungen.prototype['bilingualeSprache'] = undefined;

/**
 * @member {String} projektkursThema
 */
GOStLeistungen.prototype['projektkursThema'] = undefined;

/**
 * @member {String} projektkursLeitfach1Kuerzel
 */
GOStLeistungen.prototype['projektkursLeitfach1Kuerzel'] = undefined;

/**
 * @member {String} projektkursLeitfach2Kuerzel
 */
GOStLeistungen.prototype['projektkursLeitfach2Kuerzel'] = undefined;

/**
 * @member {Array.<module:model/GOStLeistungenFachwahl>} faecher
 */
GOStLeistungen.prototype['faecher'] = undefined;






export default GOStLeistungen;

