/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The KatalogEintrag model module.
 * @module model/KatalogEintrag
 * @version 1.0.0
 */
class KatalogEintrag {
    /**
     * Constructs a new <code>KatalogEintrag</code>.
     * ein Eintrag in einem standardisierten Katalog.
     * @alias module:model/KatalogEintrag
     * @param id {Number} die ID des Katalog-Eintrags
     * @param kuerzel {String} das Kürzel des Eintrags
     * @param text {String} die textuelle Beschreibung des Katalog-Eintrags
     * @param istSichtbar {Boolean} gibt an, ob der Eintrag in der Anwendung sichtbar sein soll oder nicht.
     * @param istAenderbar {Boolean} gibt an, ob der Eintrag in der Anwendung änderbar sein soll oder nicht.
     */
    constructor(id, kuerzel, text, istSichtbar, istAenderbar) { 
        
        KatalogEintrag.initialize(this, id, kuerzel, text, istSichtbar, istAenderbar);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, kuerzel, text, istSichtbar, istAenderbar) { 
        obj['id'] = id;
        obj['kuerzel'] = kuerzel;
        obj['text'] = text;
        obj['istSichtbar'] = istSichtbar;
        obj['istAenderbar'] = istAenderbar;
    }

    /**
     * Constructs a <code>KatalogEintrag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KatalogEintrag} obj Optional instance to populate.
     * @return {module:model/KatalogEintrag} The populated <code>KatalogEintrag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KatalogEintrag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('kuerzel')) {
                obj['kuerzel'] = ApiClient.convertToType(data['kuerzel'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('istSichtbar')) {
                obj['istSichtbar'] = ApiClient.convertToType(data['istSichtbar'], 'Boolean');
            }
            if (data.hasOwnProperty('istAenderbar')) {
                obj['istAenderbar'] = ApiClient.convertToType(data['istAenderbar'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * die ID des Katalog-Eintrags
 * @member {Number} id
 */
KatalogEintrag.prototype['id'] = undefined;

/**
 * das Kürzel des Eintrags
 * @member {String} kuerzel
 */
KatalogEintrag.prototype['kuerzel'] = undefined;

/**
 * die textuelle Beschreibung des Katalog-Eintrags
 * @member {String} text
 */
KatalogEintrag.prototype['text'] = undefined;

/**
 * gibt an, ob der Eintrag in der Anwendung sichtbar sein soll oder nicht.
 * @member {Boolean} istSichtbar
 */
KatalogEintrag.prototype['istSichtbar'] = undefined;

/**
 * gibt an, ob der Eintrag in der Anwendung änderbar sein soll oder nicht.
 * @member {Boolean} istAenderbar
 */
KatalogEintrag.prototype['istAenderbar'] = undefined;






export default KatalogEintrag;

