/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LehrerKatalogZugangsgrundEintrag model module.
 * @module model/LehrerKatalogZugangsgrundEintrag
 * @version 1.0.0
 */
class LehrerKatalogZugangsgrundEintrag {
    /**
     * Constructs a new <code>LehrerKatalogZugangsgrundEintrag</code>.
     * ein Eintrag in dem Katalog der Lehrer-Zugangsgründe.
     * @alias module:model/LehrerKatalogZugangsgrundEintrag
     * @param id {Number} die ID des Katalog-Eintrags
     * @param kuerzel {String} das Kürzel für den Zugangsgrund
     * @param text {String} der Zugangsgrund
     * @param schluessel {String} der Schlüssel für die ASD-Schulstatistik
     */
    constructor(id, kuerzel, text, schluessel) { 
        
        LehrerKatalogZugangsgrundEintrag.initialize(this, id, kuerzel, text, schluessel);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, kuerzel, text, schluessel) { 
        obj['id'] = id;
        obj['kuerzel'] = kuerzel;
        obj['text'] = text;
        obj['schluessel'] = schluessel;
    }

    /**
     * Constructs a <code>LehrerKatalogZugangsgrundEintrag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LehrerKatalogZugangsgrundEintrag} obj Optional instance to populate.
     * @return {module:model/LehrerKatalogZugangsgrundEintrag} The populated <code>LehrerKatalogZugangsgrundEintrag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LehrerKatalogZugangsgrundEintrag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('kuerzel')) {
                obj['kuerzel'] = ApiClient.convertToType(data['kuerzel'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('schluessel')) {
                obj['schluessel'] = ApiClient.convertToType(data['schluessel'], 'String');
            }
        }
        return obj;
    }


}

/**
 * die ID des Katalog-Eintrags
 * @member {Number} id
 */
LehrerKatalogZugangsgrundEintrag.prototype['id'] = undefined;

/**
 * das Kürzel für den Zugangsgrund
 * @member {String} kuerzel
 */
LehrerKatalogZugangsgrundEintrag.prototype['kuerzel'] = undefined;

/**
 * der Zugangsgrund
 * @member {String} text
 */
LehrerKatalogZugangsgrundEintrag.prototype['text'] = undefined;

/**
 * der Schlüssel für die ASD-Schulstatistik
 * @member {String} schluessel
 */
LehrerKatalogZugangsgrundEintrag.prototype['schluessel'] = undefined;






export default LehrerKatalogZugangsgrundEintrag;

