/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LehrerKatalogAbgangsgrundEintrag model module.
 * @module model/LehrerKatalogAbgangsgrundEintrag
 * @version 1.0.0
 */
class LehrerKatalogAbgangsgrundEintrag {
    /**
     * Constructs a new <code>LehrerKatalogAbgangsgrundEintrag</code>.
     * ein Eintrag in dem Katalog der Lehrer-Abgangsgründe.
     * @alias module:model/LehrerKatalogAbgangsgrundEintrag
     * @param id {Number} die ID des Katalog-Eintrags
     * @param kuerzel {String} das Kürzel für den Abgangsgrund
     * @param text {String} der Abgangsgrund
     * @param schluessel {String} der Schlüssel für die ASD-Schulstatistik
     */
    constructor(id, kuerzel, text, schluessel) { 
        
        LehrerKatalogAbgangsgrundEintrag.initialize(this, id, kuerzel, text, schluessel);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, kuerzel, text, schluessel) { 
        obj['id'] = id;
        obj['kuerzel'] = kuerzel;
        obj['text'] = text;
        obj['schluessel'] = schluessel;
    }

    /**
     * Constructs a <code>LehrerKatalogAbgangsgrundEintrag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LehrerKatalogAbgangsgrundEintrag} obj Optional instance to populate.
     * @return {module:model/LehrerKatalogAbgangsgrundEintrag} The populated <code>LehrerKatalogAbgangsgrundEintrag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LehrerKatalogAbgangsgrundEintrag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('kuerzel')) {
                obj['kuerzel'] = ApiClient.convertToType(data['kuerzel'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('schluessel')) {
                obj['schluessel'] = ApiClient.convertToType(data['schluessel'], 'String');
            }
        }
        return obj;
    }


}

/**
 * die ID des Katalog-Eintrags
 * @member {Number} id
 */
LehrerKatalogAbgangsgrundEintrag.prototype['id'] = undefined;

/**
 * das Kürzel für den Abgangsgrund
 * @member {String} kuerzel
 */
LehrerKatalogAbgangsgrundEintrag.prototype['kuerzel'] = undefined;

/**
 * der Abgangsgrund
 * @member {String} text
 */
LehrerKatalogAbgangsgrundEintrag.prototype['text'] = undefined;

/**
 * der Schlüssel für die ASD-Schulstatistik
 * @member {String} schluessel
 */
LehrerKatalogAbgangsgrundEintrag.prototype['schluessel'] = undefined;






export default LehrerKatalogAbgangsgrundEintrag;

