/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NationalitaetenKatalogEintrag model module.
 * @module model/NationalitaetenKatalogEintrag
 * @version 1.0.0
 */
class NationalitaetenKatalogEintrag {
    /**
     * Constructs a new <code>NationalitaetenKatalogEintrag</code>.
     * ein Eintrag in dem Katalog der Nationalitäten.
     * @alias module:model/NationalitaetenKatalogEintrag
     * @param id {String} das dreistellige Kürzel des Eintrages für die Statistik
     * @param land {String} die Bezeichnung des Landes
     * @param staatsangehoerigkeit {String} der Bezeichnung der Staatsangehörigkeit
     */
    constructor(id, land, staatsangehoerigkeit) { 
        
        NationalitaetenKatalogEintrag.initialize(this, id, land, staatsangehoerigkeit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, land, staatsangehoerigkeit) { 
        obj['id'] = id;
        obj['land'] = land;
        obj['staatsangehoerigkeit'] = staatsangehoerigkeit;
    }

    /**
     * Constructs a <code>NationalitaetenKatalogEintrag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NationalitaetenKatalogEintrag} obj Optional instance to populate.
     * @return {module:model/NationalitaetenKatalogEintrag} The populated <code>NationalitaetenKatalogEintrag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NationalitaetenKatalogEintrag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('land')) {
                obj['land'] = ApiClient.convertToType(data['land'], 'String');
            }
            if (data.hasOwnProperty('staatsangehoerigkeit')) {
                obj['staatsangehoerigkeit'] = ApiClient.convertToType(data['staatsangehoerigkeit'], 'String');
            }
        }
        return obj;
    }


}

/**
 * das dreistellige Kürzel des Eintrages für die Statistik
 * @member {String} id
 */
NationalitaetenKatalogEintrag.prototype['id'] = undefined;

/**
 * die Bezeichnung des Landes
 * @member {String} land
 */
NationalitaetenKatalogEintrag.prototype['land'] = undefined;

/**
 * der Bezeichnung der Staatsangehörigkeit
 * @member {String} staatsangehoerigkeit
 */
NationalitaetenKatalogEintrag.prototype['staatsangehoerigkeit'] = undefined;






export default NationalitaetenKatalogEintrag;

