/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReligionKatalogEintrag model module.
 * @module model/ReligionKatalogEintrag
 * @version 1.0.0
 */
class ReligionKatalogEintrag {
    /**
     * Constructs a new <code>ReligionKatalogEintrag</code>.
     * ein Eintrag in dem Katalog der Religionen.
     * @alias module:model/ReligionKatalogEintrag
     * @param id {Number} die ID des Katalog-Eintrags
     * @param text {String} die Bezeichnung bzw. der Name der Religion
     * @param textZeugnis {String} die Bezeichnung bzw. der Name der Religion, wie sie auf einem Zeugnis erscheint
     * @param kuerzel {String} das Kürzel des Eintrages für die Statistik
     * @param sortierung {Number} gibt die Position in der Sortierreihenfolge für die Katalog-Einträge an.
     * @param istSichtbar {Boolean} gibt an, ob der Eintrag in der Anwendung sichtbar sein soll oder nicht.
     * @param istAenderbar {Boolean} gibt an, ob der Eintrag in der Anwendung änderbar sein soll oder nicht.
     */
    constructor(id, text, textZeugnis, kuerzel, sortierung, istSichtbar, istAenderbar) { 
        
        ReligionKatalogEintrag.initialize(this, id, text, textZeugnis, kuerzel, sortierung, istSichtbar, istAenderbar);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, text, textZeugnis, kuerzel, sortierung, istSichtbar, istAenderbar) { 
        obj['id'] = id;
        obj['text'] = text;
        obj['textZeugnis'] = textZeugnis;
        obj['kuerzel'] = kuerzel;
        obj['sortierung'] = sortierung;
        obj['istSichtbar'] = istSichtbar;
        obj['istAenderbar'] = istAenderbar;
    }

    /**
     * Constructs a <code>ReligionKatalogEintrag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReligionKatalogEintrag} obj Optional instance to populate.
     * @return {module:model/ReligionKatalogEintrag} The populated <code>ReligionKatalogEintrag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReligionKatalogEintrag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('textZeugnis')) {
                obj['textZeugnis'] = ApiClient.convertToType(data['textZeugnis'], 'String');
            }
            if (data.hasOwnProperty('kuerzel')) {
                obj['kuerzel'] = ApiClient.convertToType(data['kuerzel'], 'String');
            }
            if (data.hasOwnProperty('sortierung')) {
                obj['sortierung'] = ApiClient.convertToType(data['sortierung'], 'Number');
            }
            if (data.hasOwnProperty('istSichtbar')) {
                obj['istSichtbar'] = ApiClient.convertToType(data['istSichtbar'], 'Boolean');
            }
            if (data.hasOwnProperty('istAenderbar')) {
                obj['istAenderbar'] = ApiClient.convertToType(data['istAenderbar'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * die ID des Katalog-Eintrags
 * @member {Number} id
 */
ReligionKatalogEintrag.prototype['id'] = undefined;

/**
 * die Bezeichnung bzw. der Name der Religion
 * @member {String} text
 */
ReligionKatalogEintrag.prototype['text'] = undefined;

/**
 * die Bezeichnung bzw. der Name der Religion, wie sie auf einem Zeugnis erscheint
 * @member {String} textZeugnis
 */
ReligionKatalogEintrag.prototype['textZeugnis'] = undefined;

/**
 * das Kürzel des Eintrages für die Statistik
 * @member {String} kuerzel
 */
ReligionKatalogEintrag.prototype['kuerzel'] = undefined;

/**
 * gibt die Position in der Sortierreihenfolge für die Katalog-Einträge an.
 * @member {Number} sortierung
 */
ReligionKatalogEintrag.prototype['sortierung'] = undefined;

/**
 * gibt an, ob der Eintrag in der Anwendung sichtbar sein soll oder nicht.
 * @member {Boolean} istSichtbar
 */
ReligionKatalogEintrag.prototype['istSichtbar'] = undefined;

/**
 * gibt an, ob der Eintrag in der Anwendung änderbar sein soll oder nicht.
 * @member {Boolean} istAenderbar
 */
ReligionKatalogEintrag.prototype['istAenderbar'] = undefined;






export default ReligionKatalogEintrag;

