/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SchuelerlisteEintrag model module.
 * @module model/SchuelerlisteEintrag
 * @version 1.0.0
 */
class SchuelerlisteEintrag {
    /**
     * Constructs a new <code>SchuelerlisteEintrag</code>.
     * ein Eintrag eines Schülers in der Schülerliste.
     * @alias module:model/SchuelerlisteEintrag
     * @param id {Number} die ID des Schülers
     * @param nachname {String} der Nachname des Schülers
     * @param vorname {String} der Vorname des Schülers
     * @param klasse {String} die aktuelle Klasse des Schülers
     * @param jahrgang {String} der aktuelle Jahrgang des Schülers
     * @param status {module:model/SchuelerlisteEintrag.StatusEnum} der Status des Schülers (aktiv, extern, etc.)
     */
    constructor(id, nachname, vorname, klasse, jahrgang, status) { 
        
        SchuelerlisteEintrag.initialize(this, id, nachname, vorname, klasse, jahrgang, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, nachname, vorname, klasse, jahrgang, status) { 
        obj['id'] = id;
        obj['nachname'] = nachname;
        obj['vorname'] = vorname;
        obj['klasse'] = klasse;
        obj['jahrgang'] = jahrgang;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>SchuelerlisteEintrag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SchuelerlisteEintrag} obj Optional instance to populate.
     * @return {module:model/SchuelerlisteEintrag} The populated <code>SchuelerlisteEintrag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SchuelerlisteEintrag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('nachname')) {
                obj['nachname'] = ApiClient.convertToType(data['nachname'], 'String');
            }
            if (data.hasOwnProperty('vorname')) {
                obj['vorname'] = ApiClient.convertToType(data['vorname'], 'String');
            }
            if (data.hasOwnProperty('klasse')) {
                obj['klasse'] = ApiClient.convertToType(data['klasse'], 'String');
            }
            if (data.hasOwnProperty('jahrgang')) {
                obj['jahrgang'] = ApiClient.convertToType(data['jahrgang'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * die ID des Schülers
 * @member {Number} id
 */
SchuelerlisteEintrag.prototype['id'] = undefined;

/**
 * der Nachname des Schülers
 * @member {String} nachname
 */
SchuelerlisteEintrag.prototype['nachname'] = undefined;

/**
 * der Vorname des Schülers
 * @member {String} vorname
 */
SchuelerlisteEintrag.prototype['vorname'] = undefined;

/**
 * die aktuelle Klasse des Schülers
 * @member {String} klasse
 */
SchuelerlisteEintrag.prototype['klasse'] = undefined;

/**
 * der aktuelle Jahrgang des Schülers
 * @member {String} jahrgang
 */
SchuelerlisteEintrag.prototype['jahrgang'] = undefined;

/**
 * der Status des Schülers (aktiv, extern, etc.)
 * @member {module:model/SchuelerlisteEintrag.StatusEnum} status
 */
SchuelerlisteEintrag.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
SchuelerlisteEintrag['StatusEnum'] = {

    /**
     * value: "NEUAUFNAHME"
     * @const
     */
    "NEUAUFNAHME": "NEUAUFNAHME",

    /**
     * value: "WARTELISTE"
     * @const
     */
    "WARTELISTE": "WARTELISTE",

    /**
     * value: "AKTIV"
     * @const
     */
    "AKTIV": "AKTIV",

    /**
     * value: "BEURLAUBT"
     * @const
     */
    "BEURLAUBT": "BEURLAUBT",

    /**
     * value: "EXTERN"
     * @const
     */
    "EXTERN": "EXTERN",

    /**
     * value: "ABSCHLUSS"
     * @const
     */
    "ABSCHLUSS": "ABSCHLUSS",

    /**
     * value: "ABGAENGER"
     * @const
     */
    "ABGAENGER": "ABGAENGER"
};



export default SchuelerlisteEintrag;

