/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Sprachbelegung model module.
 * @module model/Sprachbelegung
 * @version 1.0.0
 */
class Sprachbelegung {
    /**
     * Constructs a new <code>Sprachbelegung</code>.
     * @alias module:model/Sprachbelegung
     */
    constructor() { 
        
        Sprachbelegung.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Sprachbelegung</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Sprachbelegung} obj Optional instance to populate.
     * @return {module:model/Sprachbelegung} The populated <code>Sprachbelegung</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sprachbelegung();

            if (data.hasOwnProperty('fachID')) {
                obj['fachID'] = ApiClient.convertToType(data['fachID'], 'Number');
            }
            if (data.hasOwnProperty('sprache')) {
                obj['sprache'] = ApiClient.convertToType(data['sprache'], 'String');
            }
            if (data.hasOwnProperty('fachKuerzel')) {
                obj['fachKuerzel'] = ApiClient.convertToType(data['fachKuerzel'], 'String');
            }
            if (data.hasOwnProperty('reihenfolge')) {
                obj['reihenfolge'] = ApiClient.convertToType(data['reihenfolge'], 'Number');
            }
            if (data.hasOwnProperty('belegungVonJahrgang')) {
                obj['belegungVonJahrgang'] = ApiClient.convertToType(data['belegungVonJahrgang'], 'Number');
            }
            if (data.hasOwnProperty('belegungVonAbschnitt')) {
                obj['belegungVonAbschnitt'] = ApiClient.convertToType(data['belegungVonAbschnitt'], 'Number');
            }
            if (data.hasOwnProperty('belegungBisJahrgang')) {
                obj['belegungBisJahrgang'] = ApiClient.convertToType(data['belegungBisJahrgang'], 'Number');
            }
            if (data.hasOwnProperty('belegungBisAbschnitt')) {
                obj['belegungBisAbschnitt'] = ApiClient.convertToType(data['belegungBisAbschnitt'], 'Number');
            }
            if (data.hasOwnProperty('referenzniveau')) {
                obj['referenzniveau'] = ApiClient.convertToType(data['referenzniveau'], 'String');
            }
            if (data.hasOwnProperty('belegungSekI')) {
                obj['belegungSekI'] = ApiClient.convertToType(data['belegungSekI'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} fachID
 */
Sprachbelegung.prototype['fachID'] = undefined;

/**
 * @member {String} sprache
 */
Sprachbelegung.prototype['sprache'] = undefined;

/**
 * @member {String} fachKuerzel
 */
Sprachbelegung.prototype['fachKuerzel'] = undefined;

/**
 * @member {Number} reihenfolge
 */
Sprachbelegung.prototype['reihenfolge'] = undefined;

/**
 * @member {Number} belegungVonJahrgang
 */
Sprachbelegung.prototype['belegungVonJahrgang'] = undefined;

/**
 * @member {Number} belegungVonAbschnitt
 */
Sprachbelegung.prototype['belegungVonAbschnitt'] = undefined;

/**
 * @member {Number} belegungBisJahrgang
 */
Sprachbelegung.prototype['belegungBisJahrgang'] = undefined;

/**
 * @member {Number} belegungBisAbschnitt
 */
Sprachbelegung.prototype['belegungBisAbschnitt'] = undefined;

/**
 * @member {String} referenzniveau
 */
Sprachbelegung.prototype['referenzniveau'] = undefined;

/**
 * @member {module:model/Sprachbelegung.BelegungSekIEnum} belegungSekI
 */
Sprachbelegung.prototype['belegungSekI'] = undefined;





/**
 * Allowed values for the <code>belegungSekI</code> property.
 * @enum {String}
 * @readonly
 */
Sprachbelegung['BelegungSekIEnum'] = {

    /**
     * value: "NICHT_BELEGT"
     * @const
     */
    "NICHT_BELEGT": "NICHT_BELEGT",

    /**
     * value: "MIND_2_JAHRE"
     * @const
     */
    "MIND_2_JAHRE": "MIND_2_JAHRE",

    /**
     * value: "MIND_4_JAHRE"
     * @const
     */
    "MIND_4_JAHRE": "MIND_4_JAHRE",

    /**
     * value: "AB_JAHRGANG_5"
     * @const
     */
    "AB_JAHRGANG_5": "AB_JAHRGANG_5"
};



export default Sprachbelegung;

