/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Sprachbelegung from './Sprachbelegung';

/**
 * The Sprachenfolge model module.
 * @module model/Sprachenfolge
 * @version 1.0.0
 */
class Sprachenfolge {
    /**
     * Constructs a new <code>Sprachenfolge</code>.
     * Die Sprachenfolge des Schülers unter Einbeziehung der Daten aus der Sekundarstufe I.
     * @alias module:model/Sprachenfolge
     */
    constructor() { 
        
        Sprachenfolge.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Sprachenfolge</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Sprachenfolge} obj Optional instance to populate.
     * @return {module:model/Sprachenfolge} The populated <code>Sprachenfolge</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sprachenfolge();

            if (data.hasOwnProperty('sprachen')) {
                obj['sprachen'] = ApiClient.convertToType(data['sprachen'], [Sprachbelegung]);
            }
            if (data.hasOwnProperty('schueler_id')) {
                obj['schueler_id'] = ApiClient.convertToType(data['schueler_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Sprachbelegung>} sprachen
 */
Sprachenfolge.prototype['sprachen'] = undefined;

/**
 * @member {Number} schueler_id
 */
Sprachenfolge.prototype['schueler_id'] = undefined;






export default Sprachenfolge;

