/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.Abiturdaten();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Abiturdaten', function() {
    it('should create an instance of Abiturdaten', function() {
      // uncomment below and update the code to test Abiturdaten
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be.a(SvwsOpenApi.Abiturdaten);
    });

    it('should have the property schuelerId (base name: "schueler_id")', function() {
      // uncomment below and update the code to test the property schuelerId
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property schuljahrAbitur (base name: "schuljahr_abitur")', function() {
      // uncomment below and update the code to test the property schuljahrAbitur
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property fachbelegungen (base name: "fachbelegungen")', function() {
      // uncomment below and update the code to test the property fachbelegungen
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property sprachenfolge (base name: "sprachenfolge")', function() {
      // uncomment below and update the code to test the property sprachenfolge
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property bilingualeSprache (base name: "bilingualeSprache")', function() {
      // uncomment below and update the code to test the property bilingualeSprache
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property sek1Fremdsprache2ManuellGeprueft (base name: "sek1Fremdsprache2ManuellGeprueft")', function() {
      // uncomment below and update the code to test the property sek1Fremdsprache2ManuellGeprueft
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property muttersprachenpruefungEndeEF (base name: "muttersprachenpruefungEndeEF")', function() {
      // uncomment below and update the code to test the property muttersprachenpruefungEndeEF
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property latinum (base name: "latinum")', function() {
      // uncomment below and update the code to test the property latinum
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property kleinesLatinum (base name: "kleinesLatinum")', function() {
      // uncomment below and update the code to test the property kleinesLatinum
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property graecum (base name: "graecum")', function() {
      // uncomment below and update the code to test the property graecum
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property hebraicum (base name: "hebraicum")', function() {
      // uncomment below and update the code to test the property hebraicum
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1FehlstundenGesamt (base name: "block1FehlstundenGesamt")', function() {
      // uncomment below and update the code to test the property block1FehlstundenGesamt
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1FehlstundenUnentschuldigt (base name: "block1FehlstundenUnentschuldigt")', function() {
      // uncomment below and update the code to test the property block1FehlstundenUnentschuldigt
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property projektKursThema (base name: "projektKursThema")', function() {
      // uncomment below and update the code to test the property projektKursThema
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property projektkursLeitfach1Kuerzel (base name: "projektkursLeitfach1Kuerzel")', function() {
      // uncomment below and update the code to test the property projektkursLeitfach1Kuerzel
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property projektkursLeitfach2Kuerzel (base name: "projektkursLeitfach2Kuerzel")', function() {
      // uncomment below and update the code to test the property projektkursLeitfach2Kuerzel
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property besondereLernleistung (base name: "besondereLernleistung")', function() {
      // uncomment below and update the code to test the property besondereLernleistung
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property besondereLernleistungPunkte (base name: "besondereLernleistungPunkte")', function() {
      // uncomment below and update the code to test the property besondereLernleistungPunkte
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property besondereLernleistungThema (base name: "besondereLernleistungThema")', function() {
      // uncomment below and update the code to test the property besondereLernleistungThema
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1AnzahlKurse (base name: "block1AnzahlKurse")', function() {
      // uncomment below and update the code to test the property block1AnzahlKurse
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1DefiziteGesamt (base name: "block1DefiziteGesamt")', function() {
      // uncomment below and update the code to test the property block1DefiziteGesamt
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1DefiziteLK (base name: "block1DefiziteLK")', function() {
      // uncomment below and update the code to test the property block1DefiziteLK
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1PunktSummeGK (base name: "block1PunktSummeGK")', function() {
      // uncomment below and update the code to test the property block1PunktSummeGK
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1PunktSummeLK (base name: "block1PunktSummeLK")', function() {
      // uncomment below and update the code to test the property block1PunktSummeLK
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1PunktSummeNormiert (base name: "block1PunktSummeNormiert")', function() {
      // uncomment below and update the code to test the property block1PunktSummeNormiert
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1NotenpunkteDurchschnitt (base name: "block1NotenpunkteDurchschnitt")', function() {
      // uncomment below and update the code to test the property block1NotenpunkteDurchschnitt
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block1Zulassung (base name: "block1Zulassung")', function() {
      // uncomment below and update the code to test the property block1Zulassung
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property freiwilligerRuecktritt (base name: "freiwilligerRuecktritt")', function() {
      // uncomment below and update the code to test the property freiwilligerRuecktritt
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block2DefiziteGesamt (base name: "block2DefiziteGesamt")', function() {
      // uncomment below and update the code to test the property block2DefiziteGesamt
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block2DefiziteLK (base name: "block2DefiziteLK")', function() {
      // uncomment below and update the code to test the property block2DefiziteLK
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property block2PunktSumme (base name: "block2PunktSumme")', function() {
      // uncomment below and update the code to test the property block2PunktSumme
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property gesamtPunkte (base name: "gesamtPunkte")', function() {
      // uncomment below and update the code to test the property gesamtPunkte
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property gesamtPunkteVerbesserung (base name: "gesamtPunkteVerbesserung")', function() {
      // uncomment below and update the code to test the property gesamtPunkteVerbesserung
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property gesamtPunkteVerschlechterung (base name: "gesamtPunkteVerschlechterung")', function() {
      // uncomment below and update the code to test the property gesamtPunkteVerschlechterung
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property pruefungBestanden (base name: "pruefungBestanden")', function() {
      // uncomment below and update the code to test the property pruefungBestanden
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instane = new SvwsOpenApi.Abiturdaten();
      //expect(instance).to.be();
    });

  });

}));
