/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AbiturFachbelegungHalbjahr', function() {
    it('should create an instance of AbiturFachbelegungHalbjahr', function() {
      // uncomment below and update the code to test AbiturFachbelegungHalbjahr
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be.a(SvwsOpenApi.AbiturFachbelegungHalbjahr);
    });

    it('should have the property halbjahr (base name: "halbjahr")', function() {
      // uncomment below and update the code to test the property halbjahr
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property kursart (base name: "kursart")', function() {
      // uncomment below and update the code to test the property kursart
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property schriftlich (base name: "schriftlich")', function() {
      // uncomment below and update the code to test the property schriftlich
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property biliSprache (base name: "biliSprache")', function() {
      // uncomment below and update the code to test the property biliSprache
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property lehrerKuerzel (base name: "lehrerKuerzel")', function() {
      // uncomment below and update the code to test the property lehrerKuerzel
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property wochenstunden (base name: "wochenstunden")', function() {
      // uncomment below and update the code to test the property wochenstunden
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property fehlstundenGesamt (base name: "fehlstundenGesamt")', function() {
      // uncomment below and update the code to test the property fehlstundenGesamt
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property fehlstundenUnentschuldigt (base name: "fehlstundenUnentschuldigt")', function() {
      // uncomment below and update the code to test the property fehlstundenUnentschuldigt
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property block1gewertet (base name: "block1gewertet")', function() {
      // uncomment below and update the code to test the property block1gewertet
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

    it('should have the property block1kursAufZeugnis (base name: "block1kursAufZeugnis")', function() {
      // uncomment below and update the code to test the property block1kursAufZeugnis
      //var instane = new SvwsOpenApi.AbiturFachbelegungHalbjahr();
      //expect(instance).to.be();
    });

  });

}));
