/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.AbiturFachbelegung();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AbiturFachbelegung', function() {
    it('should create an instance of AbiturFachbelegung', function() {
      // uncomment below and update the code to test AbiturFachbelegung
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be.a(SvwsOpenApi.AbiturFachbelegung);
    });

    it('should have the property fach (base name: "fach")', function() {
      // uncomment below and update the code to test the property fach
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property letzteKursart (base name: "letzteKursart")', function() {
      // uncomment below and update the code to test the property letzteKursart
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property abiturFach (base name: "abiturFach")', function() {
      // uncomment below and update the code to test the property abiturFach
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property istFSNeu (base name: "istFSNeu")', function() {
      // uncomment below and update the code to test the property istFSNeu
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block1PunktSumme (base name: "block1PunktSumme")', function() {
      // uncomment below and update the code to test the property block1PunktSumme
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block1NotenpunkteDurchschnitt (base name: "block1NotenpunkteDurchschnitt")', function() {
      // uncomment below and update the code to test the property block1NotenpunkteDurchschnitt
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2NotePruefung (base name: "block2NotePruefung")', function() {
      // uncomment below and update the code to test the property block2NotePruefung
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2PunkteZwischenstand (base name: "block2PunkteZwischenstand")', function() {
      // uncomment below and update the code to test the property block2PunkteZwischenstand
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2MuendlichePruefungAbweichung (base name: "block2MuendlichePruefungAbweichung")', function() {
      // uncomment below and update the code to test the property block2MuendlichePruefungAbweichung
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2MuendlichePruefungBestehen (base name: "block2MuendlichePruefungBestehen")', function() {
      // uncomment below and update the code to test the property block2MuendlichePruefungBestehen
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2MuendlichePruefungFreiwillig (base name: "block2MuendlichePruefungFreiwillig")', function() {
      // uncomment below and update the code to test the property block2MuendlichePruefungFreiwillig
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2MuendlichePruefungReihenfolge (base name: "block2MuendlichePruefungReihenfolge")', function() {
      // uncomment below and update the code to test the property block2MuendlichePruefungReihenfolge
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2MuendlichePruefungNote (base name: "block2MuendlichePruefungNote")', function() {
      // uncomment below and update the code to test the property block2MuendlichePruefungNote
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2Punkte (base name: "block2Punkte")', function() {
      // uncomment below and update the code to test the property block2Punkte
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property block2Pruefer (base name: "block2Pruefer")', function() {
      // uncomment below and update the code to test the property block2Pruefer
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property belegungen (base name: "belegungen")', function() {
      // uncomment below and update the code to test the property belegungen
      //var instane = new SvwsOpenApi.AbiturFachbelegung();
      //expect(instance).to.be();
    });

  });

}));
