/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.FaecherlisteEintrag();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FaecherlisteEintrag', function() {
    it('should create an instance of FaecherlisteEintrag', function() {
      // uncomment below and update the code to test FaecherlisteEintrag
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be.a(SvwsOpenApi.FaecherlisteEintrag);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be();
    });

    it('should have the property kuerzel (base name: "kuerzel")', function() {
      // uncomment below and update the code to test the property kuerzel
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be();
    });

    it('should have the property kuerzelStatistik (base name: "kuerzelStatistik")', function() {
      // uncomment below and update the code to test the property kuerzelStatistik
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be();
    });

    it('should have the property bezeichnung (base name: "bezeichnung")', function() {
      // uncomment below and update the code to test the property bezeichnung
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be();
    });

    it('should have the property sortierung (base name: "sortierung")', function() {
      // uncomment below and update the code to test the property sortierung
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be();
    });

    it('should have the property istOberstufenFach (base name: "istOberstufenFach")', function() {
      // uncomment below and update the code to test the property istOberstufenFach
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be();
    });

    it('should have the property istSichtbar (base name: "istSichtbar")', function() {
      // uncomment below and update the code to test the property istSichtbar
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be();
    });

    it('should have the property istAenderbar (base name: "istAenderbar")', function() {
      // uncomment below and update the code to test the property istAenderbar
      //var instane = new SvwsOpenApi.FaecherlisteEintrag();
      //expect(instance).to.be();
    });

  });

}));
