/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.GOStLeistungenFachbelegung();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GOStLeistungenFachbelegung', function() {
    it('should create an instance of GOStLeistungenFachbelegung', function() {
      // uncomment below and update the code to test GOStLeistungenFachbelegung
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be.a(SvwsOpenApi.GOStLeistungenFachbelegung);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property schuljahr (base name: "schuljahr")', function() {
      // uncomment below and update the code to test the property schuljahr
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property halbjahr (base name: "halbjahr")', function() {
      // uncomment below and update the code to test the property halbjahr
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property abschnitt (base name: "abschnitt")', function() {
      // uncomment below and update the code to test the property abschnitt
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property abschnittGewertet (base name: "abschnittGewertet")', function() {
      // uncomment below and update the code to test the property abschnittGewertet
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property jahrgang (base name: "jahrgang")', function() {
      // uncomment below and update the code to test the property jahrgang
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property lehrerKuerzel (base name: "lehrerKuerzel")', function() {
      // uncomment below and update the code to test the property lehrerKuerzel
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property kursart (base name: "kursart")', function() {
      // uncomment below and update the code to test the property kursart
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property istSchriftlich (base name: "istSchriftlich")', function() {
      // uncomment below and update the code to test the property istSchriftlich
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property bilingualeSprache (base name: "bilingualeSprache")', function() {
      // uncomment below and update the code to test the property bilingualeSprache
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property wochenstunden (base name: "wochenstunden")', function() {
      // uncomment below and update the code to test the property wochenstunden
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property fehlstundenGesamt (base name: "fehlstundenGesamt")', function() {
      // uncomment below and update the code to test the property fehlstundenGesamt
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property fehlstundenUnentschuldigt (base name: "fehlstundenUnentschuldigt")', function() {
      // uncomment below and update the code to test the property fehlstundenUnentschuldigt
      //var instane = new SvwsOpenApi.GOStLeistungenFachbelegung();
      //expect(instance).to.be();
    });

  });

}));
