/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.GOStLeistungen();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GOStLeistungen', function() {
    it('should create an instance of GOStLeistungen', function() {
      // uncomment below and update the code to test GOStLeistungen
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be.a(SvwsOpenApi.GOStLeistungen);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

    it('should have the property aktuellesSchuljahr (base name: "aktuellesSchuljahr")', function() {
      // uncomment below and update the code to test the property aktuellesSchuljahr
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

    it('should have the property aktuellerJahrgang (base name: "aktuellerJahrgang")', function() {
      // uncomment below and update the code to test the property aktuellerJahrgang
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

    it('should have the property sprachenfolge (base name: "sprachenfolge")', function() {
      // uncomment below and update the code to test the property sprachenfolge
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

    it('should have the property bilingualeSprache (base name: "bilingualeSprache")', function() {
      // uncomment below and update the code to test the property bilingualeSprache
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

    it('should have the property projektkursThema (base name: "projektkursThema")', function() {
      // uncomment below and update the code to test the property projektkursThema
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

    it('should have the property projektkursLeitfach1Kuerzel (base name: "projektkursLeitfach1Kuerzel")', function() {
      // uncomment below and update the code to test the property projektkursLeitfach1Kuerzel
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

    it('should have the property projektkursLeitfach2Kuerzel (base name: "projektkursLeitfach2Kuerzel")', function() {
      // uncomment below and update the code to test the property projektkursLeitfach2Kuerzel
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

    it('should have the property faecher (base name: "faecher")', function() {
      // uncomment below and update the code to test the property faecher
      //var instane = new SvwsOpenApi.GOStLeistungen();
      //expect(instance).to.be();
    });

  });

}));
