/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.GOStFach();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GOStFach', function() {
    it('should create an instance of GOStFach', function() {
      // uncomment below and update the code to test GOStFach
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be.a(SvwsOpenApi.GOStFach);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property kuerzel (base name: "kuerzel")', function() {
      // uncomment below and update the code to test the property kuerzel
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property kuerzelAnzeige (base name: "kuerzelAnzeige")', function() {
      // uncomment below and update the code to test the property kuerzelAnzeige
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property sortierung (base name: "sortierung")', function() {
      // uncomment below and update the code to test the property sortierung
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istFremdsprache (base name: "istFremdsprache")', function() {
      // uncomment below and update the code to test the property istFremdsprache
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istFremdSpracheNeuEinsetzendMoeglich (base name: "istFremdSpracheNeuEinsetzendMoeglich")', function() {
      // uncomment below and update the code to test the property istFremdSpracheNeuEinsetzendMoeglich
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property biliSprache (base name: "biliSprache")', function() {
      // uncomment below and update the code to test the property biliSprache
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istMoeglichAbiLK (base name: "istMoeglichAbiLK")', function() {
      // uncomment below and update the code to test the property istMoeglichAbiLK
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istMoeglichAbiGKMoeglich (base name: "istMoeglichAbiGKMoeglich")', function() {
      // uncomment below and update the code to test the property istMoeglichAbiGKMoeglich
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istMoeglichEF1 (base name: "istMoeglichEF1")', function() {
      // uncomment below and update the code to test the property istMoeglichEF1
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istMoeglichEF2 (base name: "istMoeglichEF2")', function() {
      // uncomment below and update the code to test the property istMoeglichEF2
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istMoeglichQ11 (base name: "istMoeglichQ11")', function() {
      // uncomment below and update the code to test the property istMoeglichQ11
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istMoeglichQ12 (base name: "istMoeglichQ12")', function() {
      // uncomment below and update the code to test the property istMoeglichQ12
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istMoeglichQ21 (base name: "istMoeglichQ21")', function() {
      // uncomment below and update the code to test the property istMoeglichQ21
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property istMoeglichQ22 (base name: "istMoeglichQ22")', function() {
      // uncomment below and update the code to test the property istMoeglichQ22
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property wochenstundenEF1 (base name: "wochenstundenEF1")', function() {
      // uncomment below and update the code to test the property wochenstundenEF1
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property wochenstundenEF2 (base name: "wochenstundenEF2")', function() {
      // uncomment below and update the code to test the property wochenstundenEF2
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property wochenstundenQualifikationsphase (base name: "wochenstundenQualifikationsphase")', function() {
      // uncomment below and update the code to test the property wochenstundenQualifikationsphase
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property mussSchriftlichEF1 (base name: "mussSchriftlichEF1")', function() {
      // uncomment below and update the code to test the property mussSchriftlichEF1
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property mussSchriftlichEF2 (base name: "mussSchriftlichEF2")', function() {
      // uncomment below and update the code to test the property mussSchriftlichEF2
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property projektKursLeitfach1ID (base name: "projektKursLeitfach1ID")', function() {
      // uncomment below and update the code to test the property projektKursLeitfach1ID
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property projektKursLeitfach1Kuerzel (base name: "projektKursLeitfach1Kuerzel")', function() {
      // uncomment below and update the code to test the property projektKursLeitfach1Kuerzel
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property projektKursLeitfach2ID (base name: "projektKursLeitfach2ID")', function() {
      // uncomment below and update the code to test the property projektKursLeitfach2ID
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

    it('should have the property projektKursLeitfach2Kuerzel (base name: "projektKursLeitfach2Kuerzel")', function() {
      // uncomment below and update the code to test the property projektKursLeitfach2Kuerzel
      //var instane = new SvwsOpenApi.GOStFach();
      //expect(instance).to.be();
    });

  });

}));
