/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.LehrerStammdaten();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LehrerStammdaten', function() {
    it('should create an instance of LehrerStammdaten', function() {
      // uncomment below and update the code to test LehrerStammdaten
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be.a(SvwsOpenApi.LehrerStammdaten);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property kuerzel (base name: "kuerzel")', function() {
      // uncomment below and update the code to test the property kuerzel
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property personalTyp (base name: "personalTyp")', function() {
      // uncomment below and update the code to test the property personalTyp
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property anrede (base name: "anrede")', function() {
      // uncomment below and update the code to test the property anrede
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property titel (base name: "titel")', function() {
      // uncomment below and update the code to test the property titel
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property amtsbezeichnung (base name: "amtsbezeichnung")', function() {
      // uncomment below and update the code to test the property amtsbezeichnung
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property nachname (base name: "nachname")', function() {
      // uncomment below and update the code to test the property nachname
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property vorname (base name: "vorname")', function() {
      // uncomment below and update the code to test the property vorname
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geschlecht (base name: "geschlecht")', function() {
      // uncomment below and update the code to test the property geschlecht
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geburtsdatum (base name: "geburtsdatum")', function() {
      // uncomment below and update the code to test the property geburtsdatum
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property staatsangehoerigkeitID (base name: "staatsangehoerigkeitID")', function() {
      // uncomment below and update the code to test the property staatsangehoerigkeitID
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property strasse (base name: "strasse")', function() {
      // uncomment below and update the code to test the property strasse
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property wohnortID (base name: "wohnortID")', function() {
      // uncomment below and update the code to test the property wohnortID
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property ortsteilID (base name: "ortsteilID")', function() {
      // uncomment below and update the code to test the property ortsteilID
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property telefon (base name: "telefon")', function() {
      // uncomment below and update the code to test the property telefon
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property telefonMobil (base name: "telefonMobil")', function() {
      // uncomment below and update the code to test the property telefonMobil
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property emailPrivat (base name: "emailPrivat")', function() {
      // uncomment below and update the code to test the property emailPrivat
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property emailDienstlich (base name: "emailDienstlich")', function() {
      // uncomment below and update the code to test the property emailDienstlich
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property foto (base name: "foto")', function() {
      // uncomment below and update the code to test the property foto
      //var instane = new SvwsOpenApi.LehrerStammdaten();
      //expect(instance).to.be();
    });

  });

}));
