/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.LehrerKatalogLeitungsfunktionEintrag();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LehrerKatalogLeitungsfunktionEintrag', function() {
    it('should create an instance of LehrerKatalogLeitungsfunktionEintrag', function() {
      // uncomment below and update the code to test LehrerKatalogLeitungsfunktionEintrag
      //var instane = new SvwsOpenApi.LehrerKatalogLeitungsfunktionEintrag();
      //expect(instance).to.be.a(SvwsOpenApi.LehrerKatalogLeitungsfunktionEintrag);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SvwsOpenApi.LehrerKatalogLeitungsfunktionEintrag();
      //expect(instance).to.be();
    });

    it('should have the property kuerzel (base name: "kuerzel")', function() {
      // uncomment below and update the code to test the property kuerzel
      //var instane = new SvwsOpenApi.LehrerKatalogLeitungsfunktionEintrag();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new SvwsOpenApi.LehrerKatalogLeitungsfunktionEintrag();
      //expect(instance).to.be();
    });

  });

}));
