/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.SchuelerStammdaten();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SchuelerStammdaten', function() {
    it('should create an instance of SchuelerStammdaten', function() {
      // uncomment below and update the code to test SchuelerStammdaten
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be.a(SvwsOpenApi.SchuelerStammdaten);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property foto (base name: "foto")', function() {
      // uncomment below and update the code to test the property foto
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property nachname (base name: "nachname")', function() {
      // uncomment below and update the code to test the property nachname
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property zusatzNachname (base name: "zusatzNachname")', function() {
      // uncomment below and update the code to test the property zusatzNachname
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property vorname (base name: "vorname")', function() {
      // uncomment below and update the code to test the property vorname
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property alleVornamen (base name: "alleVornamen")', function() {
      // uncomment below and update the code to test the property alleVornamen
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geschlecht (base name: "geschlecht")', function() {
      // uncomment below and update the code to test the property geschlecht
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geburtsdatum (base name: "geburtsdatum")', function() {
      // uncomment below and update the code to test the property geburtsdatum
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geburtsort (base name: "geburtsort")', function() {
      // uncomment below and update the code to test the property geburtsort
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geburtsname (base name: "geburtsname")', function() {
      // uncomment below and update the code to test the property geburtsname
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property strasse (base name: "strasse")', function() {
      // uncomment below and update the code to test the property strasse
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property wohnortID (base name: "wohnortID")', function() {
      // uncomment below and update the code to test the property wohnortID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property ortsteilID (base name: "ortsteilID")', function() {
      // uncomment below and update the code to test the property ortsteilID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property telefon (base name: "telefon")', function() {
      // uncomment below and update the code to test the property telefon
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property telefonMobil (base name: "telefonMobil")', function() {
      // uncomment below and update the code to test the property telefonMobil
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property emailPrivat (base name: "emailPrivat")', function() {
      // uncomment below and update the code to test the property emailPrivat
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property emailSchule (base name: "emailSchule")', function() {
      // uncomment below and update the code to test the property emailSchule
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property staatsangehoerigkeitID (base name: "staatsangehoerigkeitID")', function() {
      // uncomment below and update the code to test the property staatsangehoerigkeitID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property staatsangehoerigkeit2ID (base name: "staatsangehoerigkeit2ID")', function() {
      // uncomment below and update the code to test the property staatsangehoerigkeit2ID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property religionID (base name: "religionID")', function() {
      // uncomment below and update the code to test the property religionID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property druckeKonfessionAufZeugnisse (base name: "druckeKonfessionAufZeugnisse")', function() {
      // uncomment below and update the code to test the property druckeKonfessionAufZeugnisse
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property religionabmeldung (base name: "religionabmeldung")', function() {
      // uncomment below and update the code to test the property religionabmeldung
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property religionanmeldung (base name: "religionanmeldung")', function() {
      // uncomment below and update the code to test the property religionanmeldung
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property hatMigrationshintergrund (base name: "hatMigrationshintergrund")', function() {
      // uncomment below and update the code to test the property hatMigrationshintergrund
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property zuzugsjahr (base name: "zuzugsjahr")', function() {
      // uncomment below and update the code to test the property zuzugsjahr
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geburtsland (base name: "geburtsland")', function() {
      // uncomment below and update the code to test the property geburtsland
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property verkehrspracheFamilie (base name: "verkehrspracheFamilie")', function() {
      // uncomment below and update the code to test the property verkehrspracheFamilie
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geburtslandVater (base name: "geburtslandVater")', function() {
      // uncomment below and update the code to test the property geburtslandVater
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property geburtslandMutter (base name: "geburtslandMutter")', function() {
      // uncomment below and update the code to test the property geburtslandMutter
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property foerderschwerpunktID (base name: "foerderschwerpunktID")', function() {
      // uncomment below and update the code to test the property foerderschwerpunktID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property foerderschwerpunkt2ID (base name: "foerderschwerpunkt2ID")', function() {
      // uncomment below and update the code to test the property foerderschwerpunkt2ID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property istAOSF (base name: "istAOSF")', function() {
      // uncomment below and update the code to test the property istAOSF
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property istLernenZieldifferent (base name: "istLernenZieldifferent")', function() {
      // uncomment below and update the code to test the property istLernenZieldifferent
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property fahrschuelerArtID (base name: "fahrschuelerArtID")', function() {
      // uncomment below and update the code to test the property fahrschuelerArtID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property haltestelleID (base name: "haltestelleID")', function() {
      // uncomment below and update the code to test the property haltestelleID
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property anmeldedatum (base name: "anmeldedatum")', function() {
      // uncomment below and update the code to test the property anmeldedatum
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property aufnahmedatum (base name: "aufnahmedatum")', function() {
      // uncomment below and update the code to test the property aufnahmedatum
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property istVolljaehrig (base name: "istVolljaehrig")', function() {
      // uncomment below and update the code to test the property istVolljaehrig
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property istSchulpflichtErfuellt (base name: "istSchulpflichtErfuellt")', function() {
      // uncomment below and update the code to test the property istSchulpflichtErfuellt
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property istBerufsschulpflichtErfuellt (base name: "istBerufsschulpflichtErfuellt")', function() {
      // uncomment below and update the code to test the property istBerufsschulpflichtErfuellt
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property hatMasernimpfnachweis (base name: "hatMasernimpfnachweis")', function() {
      // uncomment below and update the code to test the property hatMasernimpfnachweis
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property keineAuskunftAnDritte (base name: "keineAuskunftAnDritte")', function() {
      // uncomment below and update the code to test the property keineAuskunftAnDritte
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property erhaeltSchuelerBAFOEG (base name: "erhaeltSchuelerBAFOEG")', function() {
      // uncomment below and update the code to test the property erhaeltSchuelerBAFOEG
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property erhaeltMeisterBAFOEG (base name: "erhaeltMeisterBAFOEG")', function() {
      // uncomment below and update the code to test the property erhaeltMeisterBAFOEG
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property istDuplikat (base name: "istDuplikat")', function() {
      // uncomment below and update the code to test the property istDuplikat
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

    it('should have the property bemerkungen (base name: "bemerkungen")', function() {
      // uncomment below and update the code to test the property bemerkungen
      //var instane = new SvwsOpenApi.SchuelerStammdaten();
      //expect(instance).to.be();
    });

  });

}));
