/**
 * SVWSOpenAPI
 * Ein Server für die Bereitstellung der Open-API eines SVWS-Servers und Anwendungen zum Zugriff auf die Daten dieses Servers auf [https://localhost](https://localhost).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SvwsOpenApi);
  }
}(this, function(expect, SvwsOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SvwsOpenApi.Sprachbelegung();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Sprachbelegung', function() {
    it('should create an instance of Sprachbelegung', function() {
      // uncomment below and update the code to test Sprachbelegung
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be.a(SvwsOpenApi.Sprachbelegung);
    });

    it('should have the property fachID (base name: "fachID")', function() {
      // uncomment below and update the code to test the property fachID
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property sprache (base name: "sprache")', function() {
      // uncomment below and update the code to test the property sprache
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property fachKuerzel (base name: "fachKuerzel")', function() {
      // uncomment below and update the code to test the property fachKuerzel
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property reihenfolge (base name: "reihenfolge")', function() {
      // uncomment below and update the code to test the property reihenfolge
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property belegungVonJahrgang (base name: "belegungVonJahrgang")', function() {
      // uncomment below and update the code to test the property belegungVonJahrgang
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property belegungVonAbschnitt (base name: "belegungVonAbschnitt")', function() {
      // uncomment below and update the code to test the property belegungVonAbschnitt
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property belegungBisJahrgang (base name: "belegungBisJahrgang")', function() {
      // uncomment below and update the code to test the property belegungBisJahrgang
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property belegungBisAbschnitt (base name: "belegungBisAbschnitt")', function() {
      // uncomment below and update the code to test the property belegungBisAbschnitt
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property referenzniveau (base name: "referenzniveau")', function() {
      // uncomment below and update the code to test the property referenzniveau
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

    it('should have the property belegungSekI (base name: "belegungSekI")', function() {
      // uncomment below and update the code to test the property belegungSekI
      //var instane = new SvwsOpenApi.Sprachbelegung();
      //expect(instance).to.be();
    });

  });

}));
